-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\Tx_OFDM\qam_validity_check.vhd
-- Created: 2023-04-08 13:30:41
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: qam_validity_check
-- Source Path: Tx_OFDM/Transmitter/qam validity check
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY qam_validity_check IS
  PORT( in_qam_re                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        in_qam_im                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        is_len_qam_valid                  :   OUT   std_logic
        );
END qam_validity_check;


ARCHITECTURE rtl OF qam_validity_check IS

  -- Signals
  SIGNAL in_qam_re_signed                 : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL in_qam_im_signed                 : signed(15 DOWNTO 0);  -- sfix16_En15

BEGIN
  in_qam_re_signed <= signed(in_qam_re);

  in_qam_im_signed <= signed(in_qam_im);

  is_len_qam_valid <= '0';

END rtl;

