vlib work
vmap -c
vcom  Transmitter_pkg.vhd
vcom  Cosine_HDL_Optimized.vhd
vcom  Sine_HDL_Optimized.vhd
vcom  qam_validity_check.vhd
vcom  SimpleDualPortRAM_generic.vhd
vcom  SDFCommutator1.vhd
vcom  RADIX22FFT_SDF1_1.vhd
vcom  RADIX22FFT_CTRL1_1.vhd
vcom  SDFCommutator2.vhd
vcom  RADIX22FFT_SDF2_2.vhd
vcom  RADIX22FFT_CTRL1_2.vhd
vcom  TWDLROM_3_1.vhd
vcom  Complex4Multiply.vhd
vcom  SDFCommutator3.vhd
vcom  RADIX22FFT_SDF1_3.vhd
vcom  RADIX22FFT_CTRL1_3.vhd
vcom  SDFCommutator4.vhd
vcom  RADIX22FFT_SDF2_4.vhd
vcom  RADIX22FFT_CTRL1_4.vhd
vcom  TWDLROM_5_1.vhd
vcom  Complex4Multiply_block.vhd
vcom  SDFCommutator5.vhd
vcom  RADIX22FFT_SDF1_5.vhd
vcom  RADIX22FFT_CTRL1_5.vhd
vcom  SDFCommutator6.vhd
vcom  RADIX22FFT_SDF2_6.vhd
vcom  RADIX22FFT_CTRL1_6.vhd
vcom  IFFT1.vhd
vcom  QPSK_Modulator_Baseband.vhd
vcom  Transmitter.vhd
