// -------------------------------------------------------------
// 
// File Name: C:\Users\acer\OneDrive\Documents\ITS CAK V2\Magang\BRIN\Progress\Matlab Simulink\HDL Coder\proyek\RSP\RSP\Correlator.v
// Created: 2023-08-06 21:50:35
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Correlator
// Source Path: RSP/RSP/Correlator
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Correlator
          (x_0,
           x_1,
           x_2,
           x_3,
           x_4,
           x_5,
           x_6,
           x_7,
           x_8,
           x_9,
           x_10,
           x_11,
           x_12,
           x_13,
           x_14,
           x_15,
           x_16,
           x_17,
           x_18,
           x_19,
           x_20,
           x_21,
           x_22,
           x_23,
           x_24,
           x_25,
           x_26,
           x_27,
           x_28,
           x_29,
           x_30,
           x_31,
           x_32,
           x_33,
           x_34,
           x_35,
           x_36,
           x_37,
           x_38,
           x_39,
           x_40,
           x_41,
           x_42,
           x_43,
           x_44,
           x_45,
           x_46,
           x_47,
           x_48,
           x_49,
           x_50,
           x_51,
           x_52,
           x_53,
           x_54,
           x_55,
           x_56,
           x_57,
           x_58,
           x_59,
           x_60,
           x_61,
           x_62,
           x_63,
           x_64,
           x_65,
           x_66,
           x_67,
           x_68,
           x_69,
           x_70,
           x_71,
           x_72,
           x_73,
           x_74,
           x_75,
           x_76,
           x_77,
           x_78,
           x_79,
           x_80,
           x_81,
           x_82,
           x_83,
           x_84,
           x_85,
           x_86,
           x_87,
           x_88,
           x_89,
           x_90,
           x_91,
           x_92,
           x_93,
           x_94,
           x_95,
           x_96,
           x_97,
           x_98,
           x_99,
           x_100,
           x_101,
           x_102,
           x_103,
           x_104,
           x_105,
           x_106,
           x_107,
           x_108,
           x_109,
           x_110,
           x_111,
           x_112,
           x_113,
           x_114,
           x_115,
           x_116,
           x_117,
           x_118,
           x_119,
           x_120,
           x_121,
           x_122,
           x_123,
           x_124,
           x_125,
           x_126,
           x_127,
           x_128,
           x_129,
           x_130,
           x_131,
           x_132,
           x_133,
           x_134,
           x_135,
           x_136,
           x_137,
           x_138,
           x_139,
           x_140,
           x_141,
           x_142,
           x_143,
           x_144,
           x_145,
           x_146,
           x_147,
           x_148,
           x_149,
           x_150,
           x_151,
           x_152,
           x_153,
           x_154,
           x_155,
           x_156,
           x_157,
           x_158,
           x_159,
           x_160,
           x_161,
           x_162,
           x_163,
           x_164,
           x_165,
           x_166,
           x_167,
           x_168,
           x_169,
           x_170,
           x_171,
           x_172,
           x_173,
           x_174,
           x_175,
           x_176,
           x_177,
           x_178,
           x_179,
           x_180,
           x_181,
           x_182,
           x_183,
           x_184,
           x_185,
           x_186,
           x_187,
           x_188,
           x_189,
           x_190,
           x_191,
           x_192,
           x_193,
           x_194,
           x_195,
           x_196,
           x_197,
           x_198,
           x_199,
           x_200,
           x_201,
           x_202,
           x_203,
           x_204,
           x_205,
           x_206,
           x_207,
           x_208,
           x_209,
           x_210,
           x_211,
           x_212,
           x_213,
           x_214,
           x_215,
           x_216,
           x_217,
           x_218,
           x_219,
           x_220,
           x_221,
           x_222,
           x_223,
           x_224,
           x_225,
           x_226,
           x_227,
           x_228,
           x_229,
           x_230,
           x_231,
           x_232,
           x_233,
           x_234,
           x_235,
           x_236,
           x_237,
           x_238,
           x_239,
           x_240,
           x_241,
           x_242,
           x_243,
           x_244,
           x_245,
           x_246,
           x_247,
           x_248,
           x_249,
           x_250,
           x_251,
           x_252,
           x_253,
           x_254,
           x_255,
           y_0,
           y_1,
           y_2,
           y_3,
           y_4,
           y_5,
           y_6,
           y_7,
           y_8,
           y_9,
           y_10,
           y_11,
           y_12,
           y_13,
           y_14,
           y_15,
           y_16,
           y_17,
           y_18,
           y_19,
           y_20,
           y_21,
           y_22,
           y_23,
           y_24,
           y_25,
           y_26,
           y_27,
           y_28,
           y_29,
           y_30,
           y_31,
           y_32,
           y_33,
           y_34,
           y_35,
           y_36,
           y_37,
           y_38,
           y_39,
           y_40,
           y_41,
           y_42,
           y_43,
           y_44,
           y_45,
           y_46,
           y_47,
           y_48,
           y_49,
           y_50,
           y_51,
           y_52,
           y_53,
           y_54,
           y_55,
           y_56,
           y_57,
           y_58,
           y_59,
           y_60,
           y_61,
           y_62,
           y_63,
           y_64,
           y_65,
           y_66,
           y_67,
           y_68,
           y_69,
           y_70,
           y_71,
           y_72,
           y_73,
           y_74,
           y_75,
           y_76,
           y_77,
           y_78,
           y_79,
           y_80,
           y_81,
           y_82,
           y_83,
           y_84,
           y_85,
           y_86,
           y_87,
           y_88,
           y_89,
           y_90,
           y_91,
           y_92,
           y_93,
           y_94,
           y_95,
           y_96,
           y_97,
           y_98,
           y_99,
           y_100,
           y_101,
           y_102,
           y_103,
           y_104,
           y_105,
           y_106,
           y_107,
           y_108,
           y_109,
           y_110,
           y_111,
           y_112,
           y_113,
           y_114,
           y_115,
           y_116,
           y_117,
           y_118,
           y_119,
           y_120,
           y_121,
           y_122,
           y_123,
           y_124,
           y_125,
           y_126,
           y_127,
           y_128,
           y_129,
           y_130,
           y_131,
           y_132,
           y_133,
           y_134,
           y_135,
           y_136,
           y_137,
           y_138,
           y_139,
           y_140,
           y_141,
           y_142,
           y_143,
           y_144,
           y_145,
           y_146,
           y_147,
           y_148,
           y_149,
           y_150,
           y_151,
           y_152,
           y_153,
           y_154,
           y_155,
           y_156,
           y_157,
           y_158,
           y_159,
           y_160,
           y_161,
           y_162,
           y_163,
           y_164,
           y_165,
           y_166,
           y_167,
           y_168,
           y_169,
           y_170,
           y_171,
           y_172,
           y_173,
           y_174,
           y_175,
           y_176,
           y_177,
           y_178,
           y_179,
           y_180,
           y_181,
           y_182,
           y_183,
           y_184,
           y_185,
           y_186,
           y_187,
           y_188,
           y_189,
           y_190,
           y_191,
           y_192,
           y_193,
           y_194,
           y_195,
           y_196,
           y_197,
           y_198,
           y_199,
           y_200,
           y_201,
           y_202,
           y_203,
           y_204,
           y_205,
           y_206,
           y_207,
           y_208,
           y_209,
           y_210,
           y_211,
           y_212,
           y_213,
           y_214,
           y_215,
           y_216,
           y_217,
           y_218,
           y_219,
           y_220,
           y_221,
           y_222,
           y_223,
           y_224,
           y_225,
           y_226,
           y_227,
           y_228,
           y_229,
           y_230,
           y_231,
           y_232,
           y_233,
           y_234,
           y_235,
           y_236,
           y_237,
           y_238,
           y_239,
           y_240,
           y_241,
           y_242,
           y_243,
           y_244,
           y_245,
           y_246,
           y_247,
           y_248,
           y_249,
           y_250,
           y_251,
           y_252,
           y_253,
           y_254,
           y_255,
           max_corr,
           max_corr_lag);


  input   signed [15:0] x_0;  // sfix16_En14
  input   signed [15:0] x_1;  // sfix16_En14
  input   signed [15:0] x_2;  // sfix16_En14
  input   signed [15:0] x_3;  // sfix16_En14
  input   signed [15:0] x_4;  // sfix16_En14
  input   signed [15:0] x_5;  // sfix16_En14
  input   signed [15:0] x_6;  // sfix16_En14
  input   signed [15:0] x_7;  // sfix16_En14
  input   signed [15:0] x_8;  // sfix16_En14
  input   signed [15:0] x_9;  // sfix16_En14
  input   signed [15:0] x_10;  // sfix16_En14
  input   signed [15:0] x_11;  // sfix16_En14
  input   signed [15:0] x_12;  // sfix16_En14
  input   signed [15:0] x_13;  // sfix16_En14
  input   signed [15:0] x_14;  // sfix16_En14
  input   signed [15:0] x_15;  // sfix16_En14
  input   signed [15:0] x_16;  // sfix16_En14
  input   signed [15:0] x_17;  // sfix16_En14
  input   signed [15:0] x_18;  // sfix16_En14
  input   signed [15:0] x_19;  // sfix16_En14
  input   signed [15:0] x_20;  // sfix16_En14
  input   signed [15:0] x_21;  // sfix16_En14
  input   signed [15:0] x_22;  // sfix16_En14
  input   signed [15:0] x_23;  // sfix16_En14
  input   signed [15:0] x_24;  // sfix16_En14
  input   signed [15:0] x_25;  // sfix16_En14
  input   signed [15:0] x_26;  // sfix16_En14
  input   signed [15:0] x_27;  // sfix16_En14
  input   signed [15:0] x_28;  // sfix16_En14
  input   signed [15:0] x_29;  // sfix16_En14
  input   signed [15:0] x_30;  // sfix16_En14
  input   signed [15:0] x_31;  // sfix16_En14
  input   signed [15:0] x_32;  // sfix16_En14
  input   signed [15:0] x_33;  // sfix16_En14
  input   signed [15:0] x_34;  // sfix16_En14
  input   signed [15:0] x_35;  // sfix16_En14
  input   signed [15:0] x_36;  // sfix16_En14
  input   signed [15:0] x_37;  // sfix16_En14
  input   signed [15:0] x_38;  // sfix16_En14
  input   signed [15:0] x_39;  // sfix16_En14
  input   signed [15:0] x_40;  // sfix16_En14
  input   signed [15:0] x_41;  // sfix16_En14
  input   signed [15:0] x_42;  // sfix16_En14
  input   signed [15:0] x_43;  // sfix16_En14
  input   signed [15:0] x_44;  // sfix16_En14
  input   signed [15:0] x_45;  // sfix16_En14
  input   signed [15:0] x_46;  // sfix16_En14
  input   signed [15:0] x_47;  // sfix16_En14
  input   signed [15:0] x_48;  // sfix16_En14
  input   signed [15:0] x_49;  // sfix16_En14
  input   signed [15:0] x_50;  // sfix16_En14
  input   signed [15:0] x_51;  // sfix16_En14
  input   signed [15:0] x_52;  // sfix16_En14
  input   signed [15:0] x_53;  // sfix16_En14
  input   signed [15:0] x_54;  // sfix16_En14
  input   signed [15:0] x_55;  // sfix16_En14
  input   signed [15:0] x_56;  // sfix16_En14
  input   signed [15:0] x_57;  // sfix16_En14
  input   signed [15:0] x_58;  // sfix16_En14
  input   signed [15:0] x_59;  // sfix16_En14
  input   signed [15:0] x_60;  // sfix16_En14
  input   signed [15:0] x_61;  // sfix16_En14
  input   signed [15:0] x_62;  // sfix16_En14
  input   signed [15:0] x_63;  // sfix16_En14
  input   signed [15:0] x_64;  // sfix16_En14
  input   signed [15:0] x_65;  // sfix16_En14
  input   signed [15:0] x_66;  // sfix16_En14
  input   signed [15:0] x_67;  // sfix16_En14
  input   signed [15:0] x_68;  // sfix16_En14
  input   signed [15:0] x_69;  // sfix16_En14
  input   signed [15:0] x_70;  // sfix16_En14
  input   signed [15:0] x_71;  // sfix16_En14
  input   signed [15:0] x_72;  // sfix16_En14
  input   signed [15:0] x_73;  // sfix16_En14
  input   signed [15:0] x_74;  // sfix16_En14
  input   signed [15:0] x_75;  // sfix16_En14
  input   signed [15:0] x_76;  // sfix16_En14
  input   signed [15:0] x_77;  // sfix16_En14
  input   signed [15:0] x_78;  // sfix16_En14
  input   signed [15:0] x_79;  // sfix16_En14
  input   signed [15:0] x_80;  // sfix16_En14
  input   signed [15:0] x_81;  // sfix16_En14
  input   signed [15:0] x_82;  // sfix16_En14
  input   signed [15:0] x_83;  // sfix16_En14
  input   signed [15:0] x_84;  // sfix16_En14
  input   signed [15:0] x_85;  // sfix16_En14
  input   signed [15:0] x_86;  // sfix16_En14
  input   signed [15:0] x_87;  // sfix16_En14
  input   signed [15:0] x_88;  // sfix16_En14
  input   signed [15:0] x_89;  // sfix16_En14
  input   signed [15:0] x_90;  // sfix16_En14
  input   signed [15:0] x_91;  // sfix16_En14
  input   signed [15:0] x_92;  // sfix16_En14
  input   signed [15:0] x_93;  // sfix16_En14
  input   signed [15:0] x_94;  // sfix16_En14
  input   signed [15:0] x_95;  // sfix16_En14
  input   signed [15:0] x_96;  // sfix16_En14
  input   signed [15:0] x_97;  // sfix16_En14
  input   signed [15:0] x_98;  // sfix16_En14
  input   signed [15:0] x_99;  // sfix16_En14
  input   signed [15:0] x_100;  // sfix16_En14
  input   signed [15:0] x_101;  // sfix16_En14
  input   signed [15:0] x_102;  // sfix16_En14
  input   signed [15:0] x_103;  // sfix16_En14
  input   signed [15:0] x_104;  // sfix16_En14
  input   signed [15:0] x_105;  // sfix16_En14
  input   signed [15:0] x_106;  // sfix16_En14
  input   signed [15:0] x_107;  // sfix16_En14
  input   signed [15:0] x_108;  // sfix16_En14
  input   signed [15:0] x_109;  // sfix16_En14
  input   signed [15:0] x_110;  // sfix16_En14
  input   signed [15:0] x_111;  // sfix16_En14
  input   signed [15:0] x_112;  // sfix16_En14
  input   signed [15:0] x_113;  // sfix16_En14
  input   signed [15:0] x_114;  // sfix16_En14
  input   signed [15:0] x_115;  // sfix16_En14
  input   signed [15:0] x_116;  // sfix16_En14
  input   signed [15:0] x_117;  // sfix16_En14
  input   signed [15:0] x_118;  // sfix16_En14
  input   signed [15:0] x_119;  // sfix16_En14
  input   signed [15:0] x_120;  // sfix16_En14
  input   signed [15:0] x_121;  // sfix16_En14
  input   signed [15:0] x_122;  // sfix16_En14
  input   signed [15:0] x_123;  // sfix16_En14
  input   signed [15:0] x_124;  // sfix16_En14
  input   signed [15:0] x_125;  // sfix16_En14
  input   signed [15:0] x_126;  // sfix16_En14
  input   signed [15:0] x_127;  // sfix16_En14
  input   signed [15:0] x_128;  // sfix16_En14
  input   signed [15:0] x_129;  // sfix16_En14
  input   signed [15:0] x_130;  // sfix16_En14
  input   signed [15:0] x_131;  // sfix16_En14
  input   signed [15:0] x_132;  // sfix16_En14
  input   signed [15:0] x_133;  // sfix16_En14
  input   signed [15:0] x_134;  // sfix16_En14
  input   signed [15:0] x_135;  // sfix16_En14
  input   signed [15:0] x_136;  // sfix16_En14
  input   signed [15:0] x_137;  // sfix16_En14
  input   signed [15:0] x_138;  // sfix16_En14
  input   signed [15:0] x_139;  // sfix16_En14
  input   signed [15:0] x_140;  // sfix16_En14
  input   signed [15:0] x_141;  // sfix16_En14
  input   signed [15:0] x_142;  // sfix16_En14
  input   signed [15:0] x_143;  // sfix16_En14
  input   signed [15:0] x_144;  // sfix16_En14
  input   signed [15:0] x_145;  // sfix16_En14
  input   signed [15:0] x_146;  // sfix16_En14
  input   signed [15:0] x_147;  // sfix16_En14
  input   signed [15:0] x_148;  // sfix16_En14
  input   signed [15:0] x_149;  // sfix16_En14
  input   signed [15:0] x_150;  // sfix16_En14
  input   signed [15:0] x_151;  // sfix16_En14
  input   signed [15:0] x_152;  // sfix16_En14
  input   signed [15:0] x_153;  // sfix16_En14
  input   signed [15:0] x_154;  // sfix16_En14
  input   signed [15:0] x_155;  // sfix16_En14
  input   signed [15:0] x_156;  // sfix16_En14
  input   signed [15:0] x_157;  // sfix16_En14
  input   signed [15:0] x_158;  // sfix16_En14
  input   signed [15:0] x_159;  // sfix16_En14
  input   signed [15:0] x_160;  // sfix16_En14
  input   signed [15:0] x_161;  // sfix16_En14
  input   signed [15:0] x_162;  // sfix16_En14
  input   signed [15:0] x_163;  // sfix16_En14
  input   signed [15:0] x_164;  // sfix16_En14
  input   signed [15:0] x_165;  // sfix16_En14
  input   signed [15:0] x_166;  // sfix16_En14
  input   signed [15:0] x_167;  // sfix16_En14
  input   signed [15:0] x_168;  // sfix16_En14
  input   signed [15:0] x_169;  // sfix16_En14
  input   signed [15:0] x_170;  // sfix16_En14
  input   signed [15:0] x_171;  // sfix16_En14
  input   signed [15:0] x_172;  // sfix16_En14
  input   signed [15:0] x_173;  // sfix16_En14
  input   signed [15:0] x_174;  // sfix16_En14
  input   signed [15:0] x_175;  // sfix16_En14
  input   signed [15:0] x_176;  // sfix16_En14
  input   signed [15:0] x_177;  // sfix16_En14
  input   signed [15:0] x_178;  // sfix16_En14
  input   signed [15:0] x_179;  // sfix16_En14
  input   signed [15:0] x_180;  // sfix16_En14
  input   signed [15:0] x_181;  // sfix16_En14
  input   signed [15:0] x_182;  // sfix16_En14
  input   signed [15:0] x_183;  // sfix16_En14
  input   signed [15:0] x_184;  // sfix16_En14
  input   signed [15:0] x_185;  // sfix16_En14
  input   signed [15:0] x_186;  // sfix16_En14
  input   signed [15:0] x_187;  // sfix16_En14
  input   signed [15:0] x_188;  // sfix16_En14
  input   signed [15:0] x_189;  // sfix16_En14
  input   signed [15:0] x_190;  // sfix16_En14
  input   signed [15:0] x_191;  // sfix16_En14
  input   signed [15:0] x_192;  // sfix16_En14
  input   signed [15:0] x_193;  // sfix16_En14
  input   signed [15:0] x_194;  // sfix16_En14
  input   signed [15:0] x_195;  // sfix16_En14
  input   signed [15:0] x_196;  // sfix16_En14
  input   signed [15:0] x_197;  // sfix16_En14
  input   signed [15:0] x_198;  // sfix16_En14
  input   signed [15:0] x_199;  // sfix16_En14
  input   signed [15:0] x_200;  // sfix16_En14
  input   signed [15:0] x_201;  // sfix16_En14
  input   signed [15:0] x_202;  // sfix16_En14
  input   signed [15:0] x_203;  // sfix16_En14
  input   signed [15:0] x_204;  // sfix16_En14
  input   signed [15:0] x_205;  // sfix16_En14
  input   signed [15:0] x_206;  // sfix16_En14
  input   signed [15:0] x_207;  // sfix16_En14
  input   signed [15:0] x_208;  // sfix16_En14
  input   signed [15:0] x_209;  // sfix16_En14
  input   signed [15:0] x_210;  // sfix16_En14
  input   signed [15:0] x_211;  // sfix16_En14
  input   signed [15:0] x_212;  // sfix16_En14
  input   signed [15:0] x_213;  // sfix16_En14
  input   signed [15:0] x_214;  // sfix16_En14
  input   signed [15:0] x_215;  // sfix16_En14
  input   signed [15:0] x_216;  // sfix16_En14
  input   signed [15:0] x_217;  // sfix16_En14
  input   signed [15:0] x_218;  // sfix16_En14
  input   signed [15:0] x_219;  // sfix16_En14
  input   signed [15:0] x_220;  // sfix16_En14
  input   signed [15:0] x_221;  // sfix16_En14
  input   signed [15:0] x_222;  // sfix16_En14
  input   signed [15:0] x_223;  // sfix16_En14
  input   signed [15:0] x_224;  // sfix16_En14
  input   signed [15:0] x_225;  // sfix16_En14
  input   signed [15:0] x_226;  // sfix16_En14
  input   signed [15:0] x_227;  // sfix16_En14
  input   signed [15:0] x_228;  // sfix16_En14
  input   signed [15:0] x_229;  // sfix16_En14
  input   signed [15:0] x_230;  // sfix16_En14
  input   signed [15:0] x_231;  // sfix16_En14
  input   signed [15:0] x_232;  // sfix16_En14
  input   signed [15:0] x_233;  // sfix16_En14
  input   signed [15:0] x_234;  // sfix16_En14
  input   signed [15:0] x_235;  // sfix16_En14
  input   signed [15:0] x_236;  // sfix16_En14
  input   signed [15:0] x_237;  // sfix16_En14
  input   signed [15:0] x_238;  // sfix16_En14
  input   signed [15:0] x_239;  // sfix16_En14
  input   signed [15:0] x_240;  // sfix16_En14
  input   signed [15:0] x_241;  // sfix16_En14
  input   signed [15:0] x_242;  // sfix16_En14
  input   signed [15:0] x_243;  // sfix16_En14
  input   signed [15:0] x_244;  // sfix16_En14
  input   signed [15:0] x_245;  // sfix16_En14
  input   signed [15:0] x_246;  // sfix16_En14
  input   signed [15:0] x_247;  // sfix16_En14
  input   signed [15:0] x_248;  // sfix16_En14
  input   signed [15:0] x_249;  // sfix16_En14
  input   signed [15:0] x_250;  // sfix16_En14
  input   signed [15:0] x_251;  // sfix16_En14
  input   signed [15:0] x_252;  // sfix16_En14
  input   signed [15:0] x_253;  // sfix16_En14
  input   signed [15:0] x_254;  // sfix16_En14
  input   signed [15:0] x_255;  // sfix16_En14
  input   signed [15:0] y_0;  // sfix16_En14
  input   signed [15:0] y_1;  // sfix16_En14
  input   signed [15:0] y_2;  // sfix16_En14
  input   signed [15:0] y_3;  // sfix16_En14
  input   signed [15:0] y_4;  // sfix16_En14
  input   signed [15:0] y_5;  // sfix16_En14
  input   signed [15:0] y_6;  // sfix16_En14
  input   signed [15:0] y_7;  // sfix16_En14
  input   signed [15:0] y_8;  // sfix16_En14
  input   signed [15:0] y_9;  // sfix16_En14
  input   signed [15:0] y_10;  // sfix16_En14
  input   signed [15:0] y_11;  // sfix16_En14
  input   signed [15:0] y_12;  // sfix16_En14
  input   signed [15:0] y_13;  // sfix16_En14
  input   signed [15:0] y_14;  // sfix16_En14
  input   signed [15:0] y_15;  // sfix16_En14
  input   signed [15:0] y_16;  // sfix16_En14
  input   signed [15:0] y_17;  // sfix16_En14
  input   signed [15:0] y_18;  // sfix16_En14
  input   signed [15:0] y_19;  // sfix16_En14
  input   signed [15:0] y_20;  // sfix16_En14
  input   signed [15:0] y_21;  // sfix16_En14
  input   signed [15:0] y_22;  // sfix16_En14
  input   signed [15:0] y_23;  // sfix16_En14
  input   signed [15:0] y_24;  // sfix16_En14
  input   signed [15:0] y_25;  // sfix16_En14
  input   signed [15:0] y_26;  // sfix16_En14
  input   signed [15:0] y_27;  // sfix16_En14
  input   signed [15:0] y_28;  // sfix16_En14
  input   signed [15:0] y_29;  // sfix16_En14
  input   signed [15:0] y_30;  // sfix16_En14
  input   signed [15:0] y_31;  // sfix16_En14
  input   signed [15:0] y_32;  // sfix16_En14
  input   signed [15:0] y_33;  // sfix16_En14
  input   signed [15:0] y_34;  // sfix16_En14
  input   signed [15:0] y_35;  // sfix16_En14
  input   signed [15:0] y_36;  // sfix16_En14
  input   signed [15:0] y_37;  // sfix16_En14
  input   signed [15:0] y_38;  // sfix16_En14
  input   signed [15:0] y_39;  // sfix16_En14
  input   signed [15:0] y_40;  // sfix16_En14
  input   signed [15:0] y_41;  // sfix16_En14
  input   signed [15:0] y_42;  // sfix16_En14
  input   signed [15:0] y_43;  // sfix16_En14
  input   signed [15:0] y_44;  // sfix16_En14
  input   signed [15:0] y_45;  // sfix16_En14
  input   signed [15:0] y_46;  // sfix16_En14
  input   signed [15:0] y_47;  // sfix16_En14
  input   signed [15:0] y_48;  // sfix16_En14
  input   signed [15:0] y_49;  // sfix16_En14
  input   signed [15:0] y_50;  // sfix16_En14
  input   signed [15:0] y_51;  // sfix16_En14
  input   signed [15:0] y_52;  // sfix16_En14
  input   signed [15:0] y_53;  // sfix16_En14
  input   signed [15:0] y_54;  // sfix16_En14
  input   signed [15:0] y_55;  // sfix16_En14
  input   signed [15:0] y_56;  // sfix16_En14
  input   signed [15:0] y_57;  // sfix16_En14
  input   signed [15:0] y_58;  // sfix16_En14
  input   signed [15:0] y_59;  // sfix16_En14
  input   signed [15:0] y_60;  // sfix16_En14
  input   signed [15:0] y_61;  // sfix16_En14
  input   signed [15:0] y_62;  // sfix16_En14
  input   signed [15:0] y_63;  // sfix16_En14
  input   signed [15:0] y_64;  // sfix16_En14
  input   signed [15:0] y_65;  // sfix16_En14
  input   signed [15:0] y_66;  // sfix16_En14
  input   signed [15:0] y_67;  // sfix16_En14
  input   signed [15:0] y_68;  // sfix16_En14
  input   signed [15:0] y_69;  // sfix16_En14
  input   signed [15:0] y_70;  // sfix16_En14
  input   signed [15:0] y_71;  // sfix16_En14
  input   signed [15:0] y_72;  // sfix16_En14
  input   signed [15:0] y_73;  // sfix16_En14
  input   signed [15:0] y_74;  // sfix16_En14
  input   signed [15:0] y_75;  // sfix16_En14
  input   signed [15:0] y_76;  // sfix16_En14
  input   signed [15:0] y_77;  // sfix16_En14
  input   signed [15:0] y_78;  // sfix16_En14
  input   signed [15:0] y_79;  // sfix16_En14
  input   signed [15:0] y_80;  // sfix16_En14
  input   signed [15:0] y_81;  // sfix16_En14
  input   signed [15:0] y_82;  // sfix16_En14
  input   signed [15:0] y_83;  // sfix16_En14
  input   signed [15:0] y_84;  // sfix16_En14
  input   signed [15:0] y_85;  // sfix16_En14
  input   signed [15:0] y_86;  // sfix16_En14
  input   signed [15:0] y_87;  // sfix16_En14
  input   signed [15:0] y_88;  // sfix16_En14
  input   signed [15:0] y_89;  // sfix16_En14
  input   signed [15:0] y_90;  // sfix16_En14
  input   signed [15:0] y_91;  // sfix16_En14
  input   signed [15:0] y_92;  // sfix16_En14
  input   signed [15:0] y_93;  // sfix16_En14
  input   signed [15:0] y_94;  // sfix16_En14
  input   signed [15:0] y_95;  // sfix16_En14
  input   signed [15:0] y_96;  // sfix16_En14
  input   signed [15:0] y_97;  // sfix16_En14
  input   signed [15:0] y_98;  // sfix16_En14
  input   signed [15:0] y_99;  // sfix16_En14
  input   signed [15:0] y_100;  // sfix16_En14
  input   signed [15:0] y_101;  // sfix16_En14
  input   signed [15:0] y_102;  // sfix16_En14
  input   signed [15:0] y_103;  // sfix16_En14
  input   signed [15:0] y_104;  // sfix16_En14
  input   signed [15:0] y_105;  // sfix16_En14
  input   signed [15:0] y_106;  // sfix16_En14
  input   signed [15:0] y_107;  // sfix16_En14
  input   signed [15:0] y_108;  // sfix16_En14
  input   signed [15:0] y_109;  // sfix16_En14
  input   signed [15:0] y_110;  // sfix16_En14
  input   signed [15:0] y_111;  // sfix16_En14
  input   signed [15:0] y_112;  // sfix16_En14
  input   signed [15:0] y_113;  // sfix16_En14
  input   signed [15:0] y_114;  // sfix16_En14
  input   signed [15:0] y_115;  // sfix16_En14
  input   signed [15:0] y_116;  // sfix16_En14
  input   signed [15:0] y_117;  // sfix16_En14
  input   signed [15:0] y_118;  // sfix16_En14
  input   signed [15:0] y_119;  // sfix16_En14
  input   signed [15:0] y_120;  // sfix16_En14
  input   signed [15:0] y_121;  // sfix16_En14
  input   signed [15:0] y_122;  // sfix16_En14
  input   signed [15:0] y_123;  // sfix16_En14
  input   signed [15:0] y_124;  // sfix16_En14
  input   signed [15:0] y_125;  // sfix16_En14
  input   signed [15:0] y_126;  // sfix16_En14
  input   signed [15:0] y_127;  // sfix16_En14
  input   signed [15:0] y_128;  // sfix16_En14
  input   signed [15:0] y_129;  // sfix16_En14
  input   signed [15:0] y_130;  // sfix16_En14
  input   signed [15:0] y_131;  // sfix16_En14
  input   signed [15:0] y_132;  // sfix16_En14
  input   signed [15:0] y_133;  // sfix16_En14
  input   signed [15:0] y_134;  // sfix16_En14
  input   signed [15:0] y_135;  // sfix16_En14
  input   signed [15:0] y_136;  // sfix16_En14
  input   signed [15:0] y_137;  // sfix16_En14
  input   signed [15:0] y_138;  // sfix16_En14
  input   signed [15:0] y_139;  // sfix16_En14
  input   signed [15:0] y_140;  // sfix16_En14
  input   signed [15:0] y_141;  // sfix16_En14
  input   signed [15:0] y_142;  // sfix16_En14
  input   signed [15:0] y_143;  // sfix16_En14
  input   signed [15:0] y_144;  // sfix16_En14
  input   signed [15:0] y_145;  // sfix16_En14
  input   signed [15:0] y_146;  // sfix16_En14
  input   signed [15:0] y_147;  // sfix16_En14
  input   signed [15:0] y_148;  // sfix16_En14
  input   signed [15:0] y_149;  // sfix16_En14
  input   signed [15:0] y_150;  // sfix16_En14
  input   signed [15:0] y_151;  // sfix16_En14
  input   signed [15:0] y_152;  // sfix16_En14
  input   signed [15:0] y_153;  // sfix16_En14
  input   signed [15:0] y_154;  // sfix16_En14
  input   signed [15:0] y_155;  // sfix16_En14
  input   signed [15:0] y_156;  // sfix16_En14
  input   signed [15:0] y_157;  // sfix16_En14
  input   signed [15:0] y_158;  // sfix16_En14
  input   signed [15:0] y_159;  // sfix16_En14
  input   signed [15:0] y_160;  // sfix16_En14
  input   signed [15:0] y_161;  // sfix16_En14
  input   signed [15:0] y_162;  // sfix16_En14
  input   signed [15:0] y_163;  // sfix16_En14
  input   signed [15:0] y_164;  // sfix16_En14
  input   signed [15:0] y_165;  // sfix16_En14
  input   signed [15:0] y_166;  // sfix16_En14
  input   signed [15:0] y_167;  // sfix16_En14
  input   signed [15:0] y_168;  // sfix16_En14
  input   signed [15:0] y_169;  // sfix16_En14
  input   signed [15:0] y_170;  // sfix16_En14
  input   signed [15:0] y_171;  // sfix16_En14
  input   signed [15:0] y_172;  // sfix16_En14
  input   signed [15:0] y_173;  // sfix16_En14
  input   signed [15:0] y_174;  // sfix16_En14
  input   signed [15:0] y_175;  // sfix16_En14
  input   signed [15:0] y_176;  // sfix16_En14
  input   signed [15:0] y_177;  // sfix16_En14
  input   signed [15:0] y_178;  // sfix16_En14
  input   signed [15:0] y_179;  // sfix16_En14
  input   signed [15:0] y_180;  // sfix16_En14
  input   signed [15:0] y_181;  // sfix16_En14
  input   signed [15:0] y_182;  // sfix16_En14
  input   signed [15:0] y_183;  // sfix16_En14
  input   signed [15:0] y_184;  // sfix16_En14
  input   signed [15:0] y_185;  // sfix16_En14
  input   signed [15:0] y_186;  // sfix16_En14
  input   signed [15:0] y_187;  // sfix16_En14
  input   signed [15:0] y_188;  // sfix16_En14
  input   signed [15:0] y_189;  // sfix16_En14
  input   signed [15:0] y_190;  // sfix16_En14
  input   signed [15:0] y_191;  // sfix16_En14
  input   signed [15:0] y_192;  // sfix16_En14
  input   signed [15:0] y_193;  // sfix16_En14
  input   signed [15:0] y_194;  // sfix16_En14
  input   signed [15:0] y_195;  // sfix16_En14
  input   signed [15:0] y_196;  // sfix16_En14
  input   signed [15:0] y_197;  // sfix16_En14
  input   signed [15:0] y_198;  // sfix16_En14
  input   signed [15:0] y_199;  // sfix16_En14
  input   signed [15:0] y_200;  // sfix16_En14
  input   signed [15:0] y_201;  // sfix16_En14
  input   signed [15:0] y_202;  // sfix16_En14
  input   signed [15:0] y_203;  // sfix16_En14
  input   signed [15:0] y_204;  // sfix16_En14
  input   signed [15:0] y_205;  // sfix16_En14
  input   signed [15:0] y_206;  // sfix16_En14
  input   signed [15:0] y_207;  // sfix16_En14
  input   signed [15:0] y_208;  // sfix16_En14
  input   signed [15:0] y_209;  // sfix16_En14
  input   signed [15:0] y_210;  // sfix16_En14
  input   signed [15:0] y_211;  // sfix16_En14
  input   signed [15:0] y_212;  // sfix16_En14
  input   signed [15:0] y_213;  // sfix16_En14
  input   signed [15:0] y_214;  // sfix16_En14
  input   signed [15:0] y_215;  // sfix16_En14
  input   signed [15:0] y_216;  // sfix16_En14
  input   signed [15:0] y_217;  // sfix16_En14
  input   signed [15:0] y_218;  // sfix16_En14
  input   signed [15:0] y_219;  // sfix16_En14
  input   signed [15:0] y_220;  // sfix16_En14
  input   signed [15:0] y_221;  // sfix16_En14
  input   signed [15:0] y_222;  // sfix16_En14
  input   signed [15:0] y_223;  // sfix16_En14
  input   signed [15:0] y_224;  // sfix16_En14
  input   signed [15:0] y_225;  // sfix16_En14
  input   signed [15:0] y_226;  // sfix16_En14
  input   signed [15:0] y_227;  // sfix16_En14
  input   signed [15:0] y_228;  // sfix16_En14
  input   signed [15:0] y_229;  // sfix16_En14
  input   signed [15:0] y_230;  // sfix16_En14
  input   signed [15:0] y_231;  // sfix16_En14
  input   signed [15:0] y_232;  // sfix16_En14
  input   signed [15:0] y_233;  // sfix16_En14
  input   signed [15:0] y_234;  // sfix16_En14
  input   signed [15:0] y_235;  // sfix16_En14
  input   signed [15:0] y_236;  // sfix16_En14
  input   signed [15:0] y_237;  // sfix16_En14
  input   signed [15:0] y_238;  // sfix16_En14
  input   signed [15:0] y_239;  // sfix16_En14
  input   signed [15:0] y_240;  // sfix16_En14
  input   signed [15:0] y_241;  // sfix16_En14
  input   signed [15:0] y_242;  // sfix16_En14
  input   signed [15:0] y_243;  // sfix16_En14
  input   signed [15:0] y_244;  // sfix16_En14
  input   signed [15:0] y_245;  // sfix16_En14
  input   signed [15:0] y_246;  // sfix16_En14
  input   signed [15:0] y_247;  // sfix16_En14
  input   signed [15:0] y_248;  // sfix16_En14
  input   signed [15:0] y_249;  // sfix16_En14
  input   signed [15:0] y_250;  // sfix16_En14
  input   signed [15:0] y_251;  // sfix16_En14
  input   signed [15:0] y_252;  // sfix16_En14
  input   signed [15:0] y_253;  // sfix16_En14
  input   signed [15:0] y_254;  // sfix16_En14
  input   signed [15:0] y_255;  // sfix16_En14
  output  signed [31:0] max_corr;  // sfix32_En31
  output  signed [31:0] max_corr_lag;  // int32


  wire signed [15:0] x [0:255];  // sfix16_En14 [256]
  wire signed [15:0] y [0:255];  // sfix16_En14 [256]
  reg signed [31:0] max_corr_1;  // sfix32_En31
  reg signed [31:0] max_corr_lag_1;  // int32
  reg signed [31:0] max;  // sfix32_En31
  reg signed [31:0] m;  // sfix32
  reg signed [32:0] len_xcorr;  // sfix33
  reg signed [32:0] n;  // sfix33
  reg signed [31:0] m_0;  // int32
  reg signed [31:0] b1;  // sfix32_En28
  reg signed [31:0] c1;  // sfix32_En31
  reg signed [31:0] n_0;  // int32
  reg signed [31:0] t_0 [0:255];  // sfix32 [256]
  reg signed [31:0] add_temp [0:254];  // int32 [255]
  reg signed [32:0] sub_temp [0:254];  // sfix33 [255]
  reg signed [31:0] add_cast [0:254];  // sfix32_En31 [255]
  reg signed [32:0] t_1 [0:255];  // sfix33 [256]
  reg signed [31:0] t_2 [0:255] [0:254];  // int32 [256x255]
  reg signed [32:0] t_3 [0:255] [0:254];  // sfix33 [256x255]


  assign x[0] = x_0;
  assign x[1] = x_1;
  assign x[2] = x_2;
  assign x[3] = x_3;
  assign x[4] = x_4;
  assign x[5] = x_5;
  assign x[6] = x_6;
  assign x[7] = x_7;
  assign x[8] = x_8;
  assign x[9] = x_9;
  assign x[10] = x_10;
  assign x[11] = x_11;
  assign x[12] = x_12;
  assign x[13] = x_13;
  assign x[14] = x_14;
  assign x[15] = x_15;
  assign x[16] = x_16;
  assign x[17] = x_17;
  assign x[18] = x_18;
  assign x[19] = x_19;
  assign x[20] = x_20;
  assign x[21] = x_21;
  assign x[22] = x_22;
  assign x[23] = x_23;
  assign x[24] = x_24;
  assign x[25] = x_25;
  assign x[26] = x_26;
  assign x[27] = x_27;
  assign x[28] = x_28;
  assign x[29] = x_29;
  assign x[30] = x_30;
  assign x[31] = x_31;
  assign x[32] = x_32;
  assign x[33] = x_33;
  assign x[34] = x_34;
  assign x[35] = x_35;
  assign x[36] = x_36;
  assign x[37] = x_37;
  assign x[38] = x_38;
  assign x[39] = x_39;
  assign x[40] = x_40;
  assign x[41] = x_41;
  assign x[42] = x_42;
  assign x[43] = x_43;
  assign x[44] = x_44;
  assign x[45] = x_45;
  assign x[46] = x_46;
  assign x[47] = x_47;
  assign x[48] = x_48;
  assign x[49] = x_49;
  assign x[50] = x_50;
  assign x[51] = x_51;
  assign x[52] = x_52;
  assign x[53] = x_53;
  assign x[54] = x_54;
  assign x[55] = x_55;
  assign x[56] = x_56;
  assign x[57] = x_57;
  assign x[58] = x_58;
  assign x[59] = x_59;
  assign x[60] = x_60;
  assign x[61] = x_61;
  assign x[62] = x_62;
  assign x[63] = x_63;
  assign x[64] = x_64;
  assign x[65] = x_65;
  assign x[66] = x_66;
  assign x[67] = x_67;
  assign x[68] = x_68;
  assign x[69] = x_69;
  assign x[70] = x_70;
  assign x[71] = x_71;
  assign x[72] = x_72;
  assign x[73] = x_73;
  assign x[74] = x_74;
  assign x[75] = x_75;
  assign x[76] = x_76;
  assign x[77] = x_77;
  assign x[78] = x_78;
  assign x[79] = x_79;
  assign x[80] = x_80;
  assign x[81] = x_81;
  assign x[82] = x_82;
  assign x[83] = x_83;
  assign x[84] = x_84;
  assign x[85] = x_85;
  assign x[86] = x_86;
  assign x[87] = x_87;
  assign x[88] = x_88;
  assign x[89] = x_89;
  assign x[90] = x_90;
  assign x[91] = x_91;
  assign x[92] = x_92;
  assign x[93] = x_93;
  assign x[94] = x_94;
  assign x[95] = x_95;
  assign x[96] = x_96;
  assign x[97] = x_97;
  assign x[98] = x_98;
  assign x[99] = x_99;
  assign x[100] = x_100;
  assign x[101] = x_101;
  assign x[102] = x_102;
  assign x[103] = x_103;
  assign x[104] = x_104;
  assign x[105] = x_105;
  assign x[106] = x_106;
  assign x[107] = x_107;
  assign x[108] = x_108;
  assign x[109] = x_109;
  assign x[110] = x_110;
  assign x[111] = x_111;
  assign x[112] = x_112;
  assign x[113] = x_113;
  assign x[114] = x_114;
  assign x[115] = x_115;
  assign x[116] = x_116;
  assign x[117] = x_117;
  assign x[118] = x_118;
  assign x[119] = x_119;
  assign x[120] = x_120;
  assign x[121] = x_121;
  assign x[122] = x_122;
  assign x[123] = x_123;
  assign x[124] = x_124;
  assign x[125] = x_125;
  assign x[126] = x_126;
  assign x[127] = x_127;
  assign x[128] = x_128;
  assign x[129] = x_129;
  assign x[130] = x_130;
  assign x[131] = x_131;
  assign x[132] = x_132;
  assign x[133] = x_133;
  assign x[134] = x_134;
  assign x[135] = x_135;
  assign x[136] = x_136;
  assign x[137] = x_137;
  assign x[138] = x_138;
  assign x[139] = x_139;
  assign x[140] = x_140;
  assign x[141] = x_141;
  assign x[142] = x_142;
  assign x[143] = x_143;
  assign x[144] = x_144;
  assign x[145] = x_145;
  assign x[146] = x_146;
  assign x[147] = x_147;
  assign x[148] = x_148;
  assign x[149] = x_149;
  assign x[150] = x_150;
  assign x[151] = x_151;
  assign x[152] = x_152;
  assign x[153] = x_153;
  assign x[154] = x_154;
  assign x[155] = x_155;
  assign x[156] = x_156;
  assign x[157] = x_157;
  assign x[158] = x_158;
  assign x[159] = x_159;
  assign x[160] = x_160;
  assign x[161] = x_161;
  assign x[162] = x_162;
  assign x[163] = x_163;
  assign x[164] = x_164;
  assign x[165] = x_165;
  assign x[166] = x_166;
  assign x[167] = x_167;
  assign x[168] = x_168;
  assign x[169] = x_169;
  assign x[170] = x_170;
  assign x[171] = x_171;
  assign x[172] = x_172;
  assign x[173] = x_173;
  assign x[174] = x_174;
  assign x[175] = x_175;
  assign x[176] = x_176;
  assign x[177] = x_177;
  assign x[178] = x_178;
  assign x[179] = x_179;
  assign x[180] = x_180;
  assign x[181] = x_181;
  assign x[182] = x_182;
  assign x[183] = x_183;
  assign x[184] = x_184;
  assign x[185] = x_185;
  assign x[186] = x_186;
  assign x[187] = x_187;
  assign x[188] = x_188;
  assign x[189] = x_189;
  assign x[190] = x_190;
  assign x[191] = x_191;
  assign x[192] = x_192;
  assign x[193] = x_193;
  assign x[194] = x_194;
  assign x[195] = x_195;
  assign x[196] = x_196;
  assign x[197] = x_197;
  assign x[198] = x_198;
  assign x[199] = x_199;
  assign x[200] = x_200;
  assign x[201] = x_201;
  assign x[202] = x_202;
  assign x[203] = x_203;
  assign x[204] = x_204;
  assign x[205] = x_205;
  assign x[206] = x_206;
  assign x[207] = x_207;
  assign x[208] = x_208;
  assign x[209] = x_209;
  assign x[210] = x_210;
  assign x[211] = x_211;
  assign x[212] = x_212;
  assign x[213] = x_213;
  assign x[214] = x_214;
  assign x[215] = x_215;
  assign x[216] = x_216;
  assign x[217] = x_217;
  assign x[218] = x_218;
  assign x[219] = x_219;
  assign x[220] = x_220;
  assign x[221] = x_221;
  assign x[222] = x_222;
  assign x[223] = x_223;
  assign x[224] = x_224;
  assign x[225] = x_225;
  assign x[226] = x_226;
  assign x[227] = x_227;
  assign x[228] = x_228;
  assign x[229] = x_229;
  assign x[230] = x_230;
  assign x[231] = x_231;
  assign x[232] = x_232;
  assign x[233] = x_233;
  assign x[234] = x_234;
  assign x[235] = x_235;
  assign x[236] = x_236;
  assign x[237] = x_237;
  assign x[238] = x_238;
  assign x[239] = x_239;
  assign x[240] = x_240;
  assign x[241] = x_241;
  assign x[242] = x_242;
  assign x[243] = x_243;
  assign x[244] = x_244;
  assign x[245] = x_245;
  assign x[246] = x_246;
  assign x[247] = x_247;
  assign x[248] = x_248;
  assign x[249] = x_249;
  assign x[250] = x_250;
  assign x[251] = x_251;
  assign x[252] = x_252;
  assign x[253] = x_253;
  assign x[254] = x_254;
  assign x[255] = x_255;

  assign y[0] = y_0;
  assign y[1] = y_1;
  assign y[2] = y_2;
  assign y[3] = y_3;
  assign y[4] = y_4;
  assign y[5] = y_5;
  assign y[6] = y_6;
  assign y[7] = y_7;
  assign y[8] = y_8;
  assign y[9] = y_9;
  assign y[10] = y_10;
  assign y[11] = y_11;
  assign y[12] = y_12;
  assign y[13] = y_13;
  assign y[14] = y_14;
  assign y[15] = y_15;
  assign y[16] = y_16;
  assign y[17] = y_17;
  assign y[18] = y_18;
  assign y[19] = y_19;
  assign y[20] = y_20;
  assign y[21] = y_21;
  assign y[22] = y_22;
  assign y[23] = y_23;
  assign y[24] = y_24;
  assign y[25] = y_25;
  assign y[26] = y_26;
  assign y[27] = y_27;
  assign y[28] = y_28;
  assign y[29] = y_29;
  assign y[30] = y_30;
  assign y[31] = y_31;
  assign y[32] = y_32;
  assign y[33] = y_33;
  assign y[34] = y_34;
  assign y[35] = y_35;
  assign y[36] = y_36;
  assign y[37] = y_37;
  assign y[38] = y_38;
  assign y[39] = y_39;
  assign y[40] = y_40;
  assign y[41] = y_41;
  assign y[42] = y_42;
  assign y[43] = y_43;
  assign y[44] = y_44;
  assign y[45] = y_45;
  assign y[46] = y_46;
  assign y[47] = y_47;
  assign y[48] = y_48;
  assign y[49] = y_49;
  assign y[50] = y_50;
  assign y[51] = y_51;
  assign y[52] = y_52;
  assign y[53] = y_53;
  assign y[54] = y_54;
  assign y[55] = y_55;
  assign y[56] = y_56;
  assign y[57] = y_57;
  assign y[58] = y_58;
  assign y[59] = y_59;
  assign y[60] = y_60;
  assign y[61] = y_61;
  assign y[62] = y_62;
  assign y[63] = y_63;
  assign y[64] = y_64;
  assign y[65] = y_65;
  assign y[66] = y_66;
  assign y[67] = y_67;
  assign y[68] = y_68;
  assign y[69] = y_69;
  assign y[70] = y_70;
  assign y[71] = y_71;
  assign y[72] = y_72;
  assign y[73] = y_73;
  assign y[74] = y_74;
  assign y[75] = y_75;
  assign y[76] = y_76;
  assign y[77] = y_77;
  assign y[78] = y_78;
  assign y[79] = y_79;
  assign y[80] = y_80;
  assign y[81] = y_81;
  assign y[82] = y_82;
  assign y[83] = y_83;
  assign y[84] = y_84;
  assign y[85] = y_85;
  assign y[86] = y_86;
  assign y[87] = y_87;
  assign y[88] = y_88;
  assign y[89] = y_89;
  assign y[90] = y_90;
  assign y[91] = y_91;
  assign y[92] = y_92;
  assign y[93] = y_93;
  assign y[94] = y_94;
  assign y[95] = y_95;
  assign y[96] = y_96;
  assign y[97] = y_97;
  assign y[98] = y_98;
  assign y[99] = y_99;
  assign y[100] = y_100;
  assign y[101] = y_101;
  assign y[102] = y_102;
  assign y[103] = y_103;
  assign y[104] = y_104;
  assign y[105] = y_105;
  assign y[106] = y_106;
  assign y[107] = y_107;
  assign y[108] = y_108;
  assign y[109] = y_109;
  assign y[110] = y_110;
  assign y[111] = y_111;
  assign y[112] = y_112;
  assign y[113] = y_113;
  assign y[114] = y_114;
  assign y[115] = y_115;
  assign y[116] = y_116;
  assign y[117] = y_117;
  assign y[118] = y_118;
  assign y[119] = y_119;
  assign y[120] = y_120;
  assign y[121] = y_121;
  assign y[122] = y_122;
  assign y[123] = y_123;
  assign y[124] = y_124;
  assign y[125] = y_125;
  assign y[126] = y_126;
  assign y[127] = y_127;
  assign y[128] = y_128;
  assign y[129] = y_129;
  assign y[130] = y_130;
  assign y[131] = y_131;
  assign y[132] = y_132;
  assign y[133] = y_133;
  assign y[134] = y_134;
  assign y[135] = y_135;
  assign y[136] = y_136;
  assign y[137] = y_137;
  assign y[138] = y_138;
  assign y[139] = y_139;
  assign y[140] = y_140;
  assign y[141] = y_141;
  assign y[142] = y_142;
  assign y[143] = y_143;
  assign y[144] = y_144;
  assign y[145] = y_145;
  assign y[146] = y_146;
  assign y[147] = y_147;
  assign y[148] = y_148;
  assign y[149] = y_149;
  assign y[150] = y_150;
  assign y[151] = y_151;
  assign y[152] = y_152;
  assign y[153] = y_153;
  assign y[154] = y_154;
  assign y[155] = y_155;
  assign y[156] = y_156;
  assign y[157] = y_157;
  assign y[158] = y_158;
  assign y[159] = y_159;
  assign y[160] = y_160;
  assign y[161] = y_161;
  assign y[162] = y_162;
  assign y[163] = y_163;
  assign y[164] = y_164;
  assign y[165] = y_165;
  assign y[166] = y_166;
  assign y[167] = y_167;
  assign y[168] = y_168;
  assign y[169] = y_169;
  assign y[170] = y_170;
  assign y[171] = y_171;
  assign y[172] = y_172;
  assign y[173] = y_173;
  assign y[174] = y_174;
  assign y[175] = y_175;
  assign y[176] = y_176;
  assign y[177] = y_177;
  assign y[178] = y_178;
  assign y[179] = y_179;
  assign y[180] = y_180;
  assign y[181] = y_181;
  assign y[182] = y_182;
  assign y[183] = y_183;
  assign y[184] = y_184;
  assign y[185] = y_185;
  assign y[186] = y_186;
  assign y[187] = y_187;
  assign y[188] = y_188;
  assign y[189] = y_189;
  assign y[190] = y_190;
  assign y[191] = y_191;
  assign y[192] = y_192;
  assign y[193] = y_193;
  assign y[194] = y_194;
  assign y[195] = y_195;
  assign y[196] = y_196;
  assign y[197] = y_197;
  assign y[198] = y_198;
  assign y[199] = y_199;
  assign y[200] = y_200;
  assign y[201] = y_201;
  assign y[202] = y_202;
  assign y[203] = y_203;
  assign y[204] = y_204;
  assign y[205] = y_205;
  assign y[206] = y_206;
  assign y[207] = y_207;
  assign y[208] = y_208;
  assign y[209] = y_209;
  assign y[210] = y_210;
  assign y[211] = y_211;
  assign y[212] = y_212;
  assign y[213] = y_213;
  assign y[214] = y_214;
  assign y[215] = y_215;
  assign y[216] = y_216;
  assign y[217] = y_217;
  assign y[218] = y_218;
  assign y[219] = y_219;
  assign y[220] = y_220;
  assign y[221] = y_221;
  assign y[222] = y_222;
  assign y[223] = y_223;
  assign y[224] = y_224;
  assign y[225] = y_225;
  assign y[226] = y_226;
  assign y[227] = y_227;
  assign y[228] = y_228;
  assign y[229] = y_229;
  assign y[230] = y_230;
  assign y[231] = y_231;
  assign y[232] = y_232;
  assign y[233] = y_233;
  assign y[234] = y_234;
  assign y[235] = y_235;
  assign y[236] = y_236;
  assign y[237] = y_237;
  assign y[238] = y_238;
  assign y[239] = y_239;
  assign y[240] = y_240;
  assign y[241] = y_241;
  assign y[242] = y_242;
  assign y[243] = y_243;
  assign y[244] = y_244;
  assign y[245] = y_245;
  assign y[246] = y_246;
  assign y[247] = y_247;
  assign y[248] = y_248;
  assign y[249] = y_249;
  assign y[250] = y_250;
  assign y[251] = y_251;
  assign y[252] = y_252;
  assign y[253] = y_253;
  assign y[254] = y_254;
  assign y[255] = y_255;

  always @* begin
    t_0[0] = 32'sb00000000000000000000000000000001;
    t_0[1] = 32'sb00000000000000000000000000000010;
    t_0[2] = 32'sb00000000000000000000000000000011;
    t_0[3] = 32'sb00000000000000000000000000000100;
    t_0[4] = 32'sb00000000000000000000000000000101;
    t_0[5] = 32'sb00000000000000000000000000000110;
    t_0[6] = 32'sb00000000000000000000000000000111;
    t_0[7] = 32'sb00000000000000000000000000001000;
    t_0[8] = 32'sb00000000000000000000000000001001;
    t_0[9] = 32'sb00000000000000000000000000001010;
    t_0[10] = 32'sb00000000000000000000000000001011;
    t_0[11] = 32'sb00000000000000000000000000001100;
    t_0[12] = 32'sb00000000000000000000000000001101;
    t_0[13] = 32'sb00000000000000000000000000001110;
    t_0[14] = 32'sb00000000000000000000000000001111;
    t_0[15] = 32'sb00000000000000000000000000010000;
    t_0[16] = 32'sb00000000000000000000000000010001;
    t_0[17] = 32'sb00000000000000000000000000010010;
    t_0[18] = 32'sb00000000000000000000000000010011;
    t_0[19] = 32'sb00000000000000000000000000010100;
    t_0[20] = 32'sb00000000000000000000000000010101;
    t_0[21] = 32'sb00000000000000000000000000010110;
    t_0[22] = 32'sb00000000000000000000000000010111;
    t_0[23] = 32'sb00000000000000000000000000011000;
    t_0[24] = 32'sb00000000000000000000000000011001;
    t_0[25] = 32'sb00000000000000000000000000011010;
    t_0[26] = 32'sb00000000000000000000000000011011;
    t_0[27] = 32'sb00000000000000000000000000011100;
    t_0[28] = 32'sb00000000000000000000000000011101;
    t_0[29] = 32'sb00000000000000000000000000011110;
    t_0[30] = 32'sb00000000000000000000000000011111;
    t_0[31] = 32'sb00000000000000000000000000100000;
    t_0[32] = 32'sb00000000000000000000000000100001;
    t_0[33] = 32'sb00000000000000000000000000100010;
    t_0[34] = 32'sb00000000000000000000000000100011;
    t_0[35] = 32'sb00000000000000000000000000100100;
    t_0[36] = 32'sb00000000000000000000000000100101;
    t_0[37] = 32'sb00000000000000000000000000100110;
    t_0[38] = 32'sb00000000000000000000000000100111;
    t_0[39] = 32'sb00000000000000000000000000101000;
    t_0[40] = 32'sb00000000000000000000000000101001;
    t_0[41] = 32'sb00000000000000000000000000101010;
    t_0[42] = 32'sb00000000000000000000000000101011;
    t_0[43] = 32'sb00000000000000000000000000101100;
    t_0[44] = 32'sb00000000000000000000000000101101;
    t_0[45] = 32'sb00000000000000000000000000101110;
    t_0[46] = 32'sb00000000000000000000000000101111;
    t_0[47] = 32'sb00000000000000000000000000110000;
    t_0[48] = 32'sb00000000000000000000000000110001;
    t_0[49] = 32'sb00000000000000000000000000110010;
    t_0[50] = 32'sb00000000000000000000000000110011;
    t_0[51] = 32'sb00000000000000000000000000110100;
    t_0[52] = 32'sb00000000000000000000000000110101;
    t_0[53] = 32'sb00000000000000000000000000110110;
    t_0[54] = 32'sb00000000000000000000000000110111;
    t_0[55] = 32'sb00000000000000000000000000111000;
    t_0[56] = 32'sb00000000000000000000000000111001;
    t_0[57] = 32'sb00000000000000000000000000111010;
    t_0[58] = 32'sb00000000000000000000000000111011;
    t_0[59] = 32'sb00000000000000000000000000111100;
    t_0[60] = 32'sb00000000000000000000000000111101;
    t_0[61] = 32'sb00000000000000000000000000111110;
    t_0[62] = 32'sb00000000000000000000000000111111;
    t_0[63] = 32'sb00000000000000000000000001000000;
    t_0[64] = 32'sb00000000000000000000000001000001;
    t_0[65] = 32'sb00000000000000000000000001000010;
    t_0[66] = 32'sb00000000000000000000000001000011;
    t_0[67] = 32'sb00000000000000000000000001000100;
    t_0[68] = 32'sb00000000000000000000000001000101;
    t_0[69] = 32'sb00000000000000000000000001000110;
    t_0[70] = 32'sb00000000000000000000000001000111;
    t_0[71] = 32'sb00000000000000000000000001001000;
    t_0[72] = 32'sb00000000000000000000000001001001;
    t_0[73] = 32'sb00000000000000000000000001001010;
    t_0[74] = 32'sb00000000000000000000000001001011;
    t_0[75] = 32'sb00000000000000000000000001001100;
    t_0[76] = 32'sb00000000000000000000000001001101;
    t_0[77] = 32'sb00000000000000000000000001001110;
    t_0[78] = 32'sb00000000000000000000000001001111;
    t_0[79] = 32'sb00000000000000000000000001010000;
    t_0[80] = 32'sb00000000000000000000000001010001;
    t_0[81] = 32'sb00000000000000000000000001010010;
    t_0[82] = 32'sb00000000000000000000000001010011;
    t_0[83] = 32'sb00000000000000000000000001010100;
    t_0[84] = 32'sb00000000000000000000000001010101;
    t_0[85] = 32'sb00000000000000000000000001010110;
    t_0[86] = 32'sb00000000000000000000000001010111;
    t_0[87] = 32'sb00000000000000000000000001011000;
    t_0[88] = 32'sb00000000000000000000000001011001;
    t_0[89] = 32'sb00000000000000000000000001011010;
    t_0[90] = 32'sb00000000000000000000000001011011;
    t_0[91] = 32'sb00000000000000000000000001011100;
    t_0[92] = 32'sb00000000000000000000000001011101;
    t_0[93] = 32'sb00000000000000000000000001011110;
    t_0[94] = 32'sb00000000000000000000000001011111;
    t_0[95] = 32'sb00000000000000000000000001100000;
    t_0[96] = 32'sb00000000000000000000000001100001;
    t_0[97] = 32'sb00000000000000000000000001100010;
    t_0[98] = 32'sb00000000000000000000000001100011;
    t_0[99] = 32'sb00000000000000000000000001100100;
    t_0[100] = 32'sb00000000000000000000000001100101;
    t_0[101] = 32'sb00000000000000000000000001100110;
    t_0[102] = 32'sb00000000000000000000000001100111;
    t_0[103] = 32'sb00000000000000000000000001101000;
    t_0[104] = 32'sb00000000000000000000000001101001;
    t_0[105] = 32'sb00000000000000000000000001101010;
    t_0[106] = 32'sb00000000000000000000000001101011;
    t_0[107] = 32'sb00000000000000000000000001101100;
    t_0[108] = 32'sb00000000000000000000000001101101;
    t_0[109] = 32'sb00000000000000000000000001101110;
    t_0[110] = 32'sb00000000000000000000000001101111;
    t_0[111] = 32'sb00000000000000000000000001110000;
    t_0[112] = 32'sb00000000000000000000000001110001;
    t_0[113] = 32'sb00000000000000000000000001110010;
    t_0[114] = 32'sb00000000000000000000000001110011;
    t_0[115] = 32'sb00000000000000000000000001110100;
    t_0[116] = 32'sb00000000000000000000000001110101;
    t_0[117] = 32'sb00000000000000000000000001110110;
    t_0[118] = 32'sb00000000000000000000000001110111;
    t_0[119] = 32'sb00000000000000000000000001111000;
    t_0[120] = 32'sb00000000000000000000000001111001;
    t_0[121] = 32'sb00000000000000000000000001111010;
    t_0[122] = 32'sb00000000000000000000000001111011;
    t_0[123] = 32'sb00000000000000000000000001111100;
    t_0[124] = 32'sb00000000000000000000000001111101;
    t_0[125] = 32'sb00000000000000000000000001111110;
    t_0[126] = 32'sb00000000000000000000000001111111;
    t_0[127] = 32'sb00000000000000000000000010000000;
    t_0[128] = 32'sb00000000000000000000000010000001;
    t_0[129] = 32'sb00000000000000000000000010000010;
    t_0[130] = 32'sb00000000000000000000000010000011;
    t_0[131] = 32'sb00000000000000000000000010000100;
    t_0[132] = 32'sb00000000000000000000000010000101;
    t_0[133] = 32'sb00000000000000000000000010000110;
    t_0[134] = 32'sb00000000000000000000000010000111;
    t_0[135] = 32'sb00000000000000000000000010001000;
    t_0[136] = 32'sb00000000000000000000000010001001;
    t_0[137] = 32'sb00000000000000000000000010001010;
    t_0[138] = 32'sb00000000000000000000000010001011;
    t_0[139] = 32'sb00000000000000000000000010001100;
    t_0[140] = 32'sb00000000000000000000000010001101;
    t_0[141] = 32'sb00000000000000000000000010001110;
    t_0[142] = 32'sb00000000000000000000000010001111;
    t_0[143] = 32'sb00000000000000000000000010010000;
    t_0[144] = 32'sb00000000000000000000000010010001;
    t_0[145] = 32'sb00000000000000000000000010010010;
    t_0[146] = 32'sb00000000000000000000000010010011;
    t_0[147] = 32'sb00000000000000000000000010010100;
    t_0[148] = 32'sb00000000000000000000000010010101;
    t_0[149] = 32'sb00000000000000000000000010010110;
    t_0[150] = 32'sb00000000000000000000000010010111;
    t_0[151] = 32'sb00000000000000000000000010011000;
    t_0[152] = 32'sb00000000000000000000000010011001;
    t_0[153] = 32'sb00000000000000000000000010011010;
    t_0[154] = 32'sb00000000000000000000000010011011;
    t_0[155] = 32'sb00000000000000000000000010011100;
    t_0[156] = 32'sb00000000000000000000000010011101;
    t_0[157] = 32'sb00000000000000000000000010011110;
    t_0[158] = 32'sb00000000000000000000000010011111;
    t_0[159] = 32'sb00000000000000000000000010100000;
    t_0[160] = 32'sb00000000000000000000000010100001;
    t_0[161] = 32'sb00000000000000000000000010100010;
    t_0[162] = 32'sb00000000000000000000000010100011;
    t_0[163] = 32'sb00000000000000000000000010100100;
    t_0[164] = 32'sb00000000000000000000000010100101;
    t_0[165] = 32'sb00000000000000000000000010100110;
    t_0[166] = 32'sb00000000000000000000000010100111;
    t_0[167] = 32'sb00000000000000000000000010101000;
    t_0[168] = 32'sb00000000000000000000000010101001;
    t_0[169] = 32'sb00000000000000000000000010101010;
    t_0[170] = 32'sb00000000000000000000000010101011;
    t_0[171] = 32'sb00000000000000000000000010101100;
    t_0[172] = 32'sb00000000000000000000000010101101;
    t_0[173] = 32'sb00000000000000000000000010101110;
    t_0[174] = 32'sb00000000000000000000000010101111;
    t_0[175] = 32'sb00000000000000000000000010110000;
    t_0[176] = 32'sb00000000000000000000000010110001;
    t_0[177] = 32'sb00000000000000000000000010110010;
    t_0[178] = 32'sb00000000000000000000000010110011;
    t_0[179] = 32'sb00000000000000000000000010110100;
    t_0[180] = 32'sb00000000000000000000000010110101;
    t_0[181] = 32'sb00000000000000000000000010110110;
    t_0[182] = 32'sb00000000000000000000000010110111;
    t_0[183] = 32'sb00000000000000000000000010111000;
    t_0[184] = 32'sb00000000000000000000000010111001;
    t_0[185] = 32'sb00000000000000000000000010111010;
    t_0[186] = 32'sb00000000000000000000000010111011;
    t_0[187] = 32'sb00000000000000000000000010111100;
    t_0[188] = 32'sb00000000000000000000000010111101;
    t_0[189] = 32'sb00000000000000000000000010111110;
    t_0[190] = 32'sb00000000000000000000000010111111;
    t_0[191] = 32'sb00000000000000000000000011000000;
    t_0[192] = 32'sb00000000000000000000000011000001;
    t_0[193] = 32'sb00000000000000000000000011000010;
    t_0[194] = 32'sb00000000000000000000000011000011;
    t_0[195] = 32'sb00000000000000000000000011000100;
    t_0[196] = 32'sb00000000000000000000000011000101;
    t_0[197] = 32'sb00000000000000000000000011000110;
    t_0[198] = 32'sb00000000000000000000000011000111;
    t_0[199] = 32'sb00000000000000000000000011001000;
    t_0[200] = 32'sb00000000000000000000000011001001;
    t_0[201] = 32'sb00000000000000000000000011001010;
    t_0[202] = 32'sb00000000000000000000000011001011;
    t_0[203] = 32'sb00000000000000000000000011001100;
    t_0[204] = 32'sb00000000000000000000000011001101;
    t_0[205] = 32'sb00000000000000000000000011001110;
    t_0[206] = 32'sb00000000000000000000000011001111;
    t_0[207] = 32'sb00000000000000000000000011010000;
    t_0[208] = 32'sb00000000000000000000000011010001;
    t_0[209] = 32'sb00000000000000000000000011010010;
    t_0[210] = 32'sb00000000000000000000000011010011;
    t_0[211] = 32'sb00000000000000000000000011010100;
    t_0[212] = 32'sb00000000000000000000000011010101;
    t_0[213] = 32'sb00000000000000000000000011010110;
    t_0[214] = 32'sb00000000000000000000000011010111;
    t_0[215] = 32'sb00000000000000000000000011011000;
    t_0[216] = 32'sb00000000000000000000000011011001;
    t_0[217] = 32'sb00000000000000000000000011011010;
    t_0[218] = 32'sb00000000000000000000000011011011;
    t_0[219] = 32'sb00000000000000000000000011011100;
    t_0[220] = 32'sb00000000000000000000000011011101;
    t_0[221] = 32'sb00000000000000000000000011011110;
    t_0[222] = 32'sb00000000000000000000000011011111;
    t_0[223] = 32'sb00000000000000000000000011100000;
    t_0[224] = 32'sb00000000000000000000000011100001;
    t_0[225] = 32'sb00000000000000000000000011100010;
    t_0[226] = 32'sb00000000000000000000000011100011;
    t_0[227] = 32'sb00000000000000000000000011100100;
    t_0[228] = 32'sb00000000000000000000000011100101;
    t_0[229] = 32'sb00000000000000000000000011100110;
    t_0[230] = 32'sb00000000000000000000000011100111;
    t_0[231] = 32'sb00000000000000000000000011101000;
    t_0[232] = 32'sb00000000000000000000000011101001;
    t_0[233] = 32'sb00000000000000000000000011101010;
    t_0[234] = 32'sb00000000000000000000000011101011;
    t_0[235] = 32'sb00000000000000000000000011101100;
    t_0[236] = 32'sb00000000000000000000000011101101;
    t_0[237] = 32'sb00000000000000000000000011101110;
    t_0[238] = 32'sb00000000000000000000000011101111;
    t_0[239] = 32'sb00000000000000000000000011110000;
    t_0[240] = 32'sb00000000000000000000000011110001;
    t_0[241] = 32'sb00000000000000000000000011110010;
    t_0[242] = 32'sb00000000000000000000000011110011;
    t_0[243] = 32'sb00000000000000000000000011110100;
    t_0[244] = 32'sb00000000000000000000000011110101;
    t_0[245] = 32'sb00000000000000000000000011110110;
    t_0[246] = 32'sb00000000000000000000000011110111;
    t_0[247] = 32'sb00000000000000000000000011111000;
    t_0[248] = 32'sb00000000000000000000000011111001;
    t_0[249] = 32'sb00000000000000000000000011111010;
    t_0[250] = 32'sb00000000000000000000000011111011;
    t_0[251] = 32'sb00000000000000000000000011111100;
    t_0[252] = 32'sb00000000000000000000000011111101;
    t_0[253] = 32'sb00000000000000000000000011111110;
    t_0[254] = 32'sb00000000000000000000000011111111;
    t_0[255] = 32'sb00000000000000000000000100000000;
    c1 = 32'sb00000000000000000000000000000000;
    m = 32'sb00000000000000000000000000000000;
    len_xcorr = 33'sh000000000;
    b1 = 32'sb00000000000000000000000000000000;
    n = 33'sh000000000;
    // tmp = y;
    max_corr_lag_1 = 32'sb00000000000000000000000000000000;
    max = 32'sb00000000000000000000000000000000;

    for(m_0 = 32'sd0; m_0 <= 32'sd255; m_0 = m_0 + 32'sd1) begin
      m = t_0[m_0];
      c1 = 32'sb00000000000000000000000000000000;
      t_1[m_0] = {m[31], m};
      len_xcorr = 33'sh000000100 - t_1[m_0];

      for(n_0 = 32'sd0; n_0 <= 32'sd254; n_0 = n_0 + 32'sd1) begin
        t_2[m_0][n_0] = len_xcorr[31:0];
        if ((n_0 + 32'sd1) <= t_2[m_0][n_0]) begin
          add_temp[n_0] = n_0 + 32'sd1;
          n = {add_temp[n_0][31], add_temp[n_0]};
          t_3[m_0][n_0] = {m[31], m};
          sub_temp[n_0] = t_3[m_0][n_0] - 33'sh000000001;
          b1 = x[(sub_temp[n_0] + n) - 32'sd1] * y[n - 32'sd1];
          add_cast[n_0] = {b1[28:0], 3'b000};
          c1 = c1 + add_cast[n_0];
        end
      end

      if (c1 > max) begin
        max = c1;
        max_corr_lag_1 = m;
      end
    end

    max_corr_1 = max;
  end



  assign max_corr = max_corr_1;

  assign max_corr_lag = max_corr_lag_1;

endmodule  // Correlator

