// -------------------------------------------------------------
// 
// File Name: C:\Users\acer\OneDrive\Documents\ITS CAK V2\Magang\BRIN\Progress\Matlab Simulink\HDL Coder\proyek\RSP\RSP\RSP\Doppler_Calculation.v
// Created: 2023-09-29 06:09:50
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Doppler_Calculation
// Source Path: RSP/RSP/Velocity Processor/Doppler Processing/Doppler Processor/Doppler Calculation
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Doppler_Calculation
          (u_0,
           u_1,
           u_2,
           u_3,
           u_4,
           u_5,
           u_6,
           u_7,
           u_8,
           u_9,
           u_10,
           u_11,
           u_12,
           u_13,
           u_14,
           u_15,
           u_16,
           u_17,
           u_18,
           u_19,
           u_20,
           u_21,
           u_22,
           u_23,
           u_24,
           u_25,
           u_26,
           u_27,
           u_28,
           u_29,
           u_30,
           u_31,
           valid,
           f);


  input   signed [34:0] u_0;  // sfix35_En20
  input   signed [34:0] u_1;  // sfix35_En20
  input   signed [34:0] u_2;  // sfix35_En20
  input   signed [34:0] u_3;  // sfix35_En20
  input   signed [34:0] u_4;  // sfix35_En20
  input   signed [34:0] u_5;  // sfix35_En20
  input   signed [34:0] u_6;  // sfix35_En20
  input   signed [34:0] u_7;  // sfix35_En20
  input   signed [34:0] u_8;  // sfix35_En20
  input   signed [34:0] u_9;  // sfix35_En20
  input   signed [34:0] u_10;  // sfix35_En20
  input   signed [34:0] u_11;  // sfix35_En20
  input   signed [34:0] u_12;  // sfix35_En20
  input   signed [34:0] u_13;  // sfix35_En20
  input   signed [34:0] u_14;  // sfix35_En20
  input   signed [34:0] u_15;  // sfix35_En20
  input   signed [34:0] u_16;  // sfix35_En20
  input   signed [34:0] u_17;  // sfix35_En20
  input   signed [34:0] u_18;  // sfix35_En20
  input   signed [34:0] u_19;  // sfix35_En20
  input   signed [34:0] u_20;  // sfix35_En20
  input   signed [34:0] u_21;  // sfix35_En20
  input   signed [34:0] u_22;  // sfix35_En20
  input   signed [34:0] u_23;  // sfix35_En20
  input   signed [34:0] u_24;  // sfix35_En20
  input   signed [34:0] u_25;  // sfix35_En20
  input   signed [34:0] u_26;  // sfix35_En20
  input   signed [34:0] u_27;  // sfix35_En20
  input   signed [34:0] u_28;  // sfix35_En20
  input   signed [34:0] u_29;  // sfix35_En20
  input   signed [34:0] u_30;  // sfix35_En20
  input   signed [34:0] u_31;  // sfix35_En20
  input   valid;
  output  [31:0] f;  // ufix32_En5


  wire signed [34:0] u [0:31];  // sfix35_En20 [32]
  reg [31:0] f_1;  // ufix32_En5
  reg [15:0] idx_max_1;  // uint16
  reg [15:0] idx_max;  // uint16
  reg signed [34:0] max_pow;  // sfix35_En20
  reg  is_found;
  reg signed [31:0] i;  // uint16
  reg [15:0] y;  // uint16
  reg [15:0] z;  // uint16
  reg signed [31:0] k;  // int32
  reg [31:0] mul_temp;  // ufix32
  reg signed [16:0] sub_cast;  // sfix17_E6
  reg signed [48:0] sub_cast_0;  // sfix49
  reg [15:0] sub_cast_1;  // uint16
  reg signed [31:0] t_0;  // int32


  assign u[0] = u_0;
  assign u[1] = u_1;
  assign u[2] = u_2;
  assign u[3] = u_3;
  assign u[4] = u_4;
  assign u[5] = u_5;
  assign u[6] = u_6;
  assign u[7] = u_7;
  assign u[8] = u_8;
  assign u[9] = u_9;
  assign u[10] = u_10;
  assign u[11] = u_11;
  assign u[12] = u_12;
  assign u[13] = u_13;
  assign u[14] = u_14;
  assign u[15] = u_15;
  assign u[16] = u_16;
  assign u[17] = u_17;
  assign u[18] = u_18;
  assign u[19] = u_19;
  assign u[20] = u_20;
  assign u[21] = u_21;
  assign u[22] = u_22;
  assign u[23] = u_23;
  assign u[24] = u_24;
  assign u[25] = u_25;
  assign u[26] = u_26;
  assign u[27] = u_27;
  assign u[28] = u_28;
  assign u[29] = u_29;
  assign u[30] = u_30;
  assign u[31] = u_31;

  always @* begin
    max_pow = u[0];

    for(k = 32'sd0; k <= 32'sd14; k = k + 32'sd1) begin
      if (max_pow < u[k + 32'sd1]) begin
        max_pow = u[k + 32'sd1];
      end
    end

    idx_max = 16'd0;
    is_found = 1'b0;
    if (valid) begin

      for(i = 16'd1; i <= 16'd16; i = i + 16'd1) begin
        if ((u[i - 32'sd1] == max_pow) &&  ! is_found) begin
          idx_max = i;
          is_found = 1'b1;
        end
      end

    end
    mul_temp = idx_max * 16'd5000;
    y = mul_temp[15:0];
    z = y >> 32'd6;
    sub_cast = {1'b0, z};
    sub_cast_0 = {{26{sub_cast[16]}}, {sub_cast, 6'b000000}};
    t_0 = sub_cast_0[31:0];
    sub_cast_1 = t_0[15:0];
    if ((y - sub_cast_1) >= 16'd32) begin
      z = z + 16'd1;
    end
    //prf/2
    f_1 = {11'b0, {z, 5'b00000}};
    idx_max_1 = idx_max;
  end



  assign f = f_1;

endmodule  // Doppler_Calculation

