// -------------------------------------------------------------
// 
// File Name: C:\Users\acer\OneDrive\Documents\ITS CAK V2\Magang\BRIN\Progress\Matlab Simulink\HDL Coder\proyek\RSP\RSP\RSP\Doppler_Processor.v
// Created: 2023-09-27 04:10:36
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Doppler_Processor
// Source Path: RSP/RSP/Velocity Processor/Doppler Processing/Doppler Processor
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Doppler_Processor
          (clk,
           reset,
           enb,
           obs_samples_0,
           obs_samples_1,
           obs_samples_2,
           obs_samples_3,
           obs_samples_4,
           obs_samples_5,
           obs_samples_6,
           obs_samples_7,
           obs_samples_8,
           obs_samples_9,
           obs_samples_10,
           obs_samples_11,
           obs_samples_12,
           obs_samples_13,
           obs_samples_14,
           obs_samples_15,
           obs_samples_16,
           obs_samples_17,
           obs_samples_18,
           obs_samples_19,
           obs_samples_20,
           obs_samples_21,
           obs_samples_22,
           obs_samples_23,
           obs_samples_24,
           obs_samples_25,
           obs_samples_26,
           obs_samples_27,
           obs_samples_28,
           obs_samples_29,
           obs_samples_30,
           obs_samples_31,
           dopp_freq);


  input   clk;
  input   reset;
  input   enb;
  input   signed [11:0] obs_samples_0;  // sfix12_En10
  input   signed [11:0] obs_samples_1;  // sfix12_En10
  input   signed [11:0] obs_samples_2;  // sfix12_En10
  input   signed [11:0] obs_samples_3;  // sfix12_En10
  input   signed [11:0] obs_samples_4;  // sfix12_En10
  input   signed [11:0] obs_samples_5;  // sfix12_En10
  input   signed [11:0] obs_samples_6;  // sfix12_En10
  input   signed [11:0] obs_samples_7;  // sfix12_En10
  input   signed [11:0] obs_samples_8;  // sfix12_En10
  input   signed [11:0] obs_samples_9;  // sfix12_En10
  input   signed [11:0] obs_samples_10;  // sfix12_En10
  input   signed [11:0] obs_samples_11;  // sfix12_En10
  input   signed [11:0] obs_samples_12;  // sfix12_En10
  input   signed [11:0] obs_samples_13;  // sfix12_En10
  input   signed [11:0] obs_samples_14;  // sfix12_En10
  input   signed [11:0] obs_samples_15;  // sfix12_En10
  input   signed [11:0] obs_samples_16;  // sfix12_En10
  input   signed [11:0] obs_samples_17;  // sfix12_En10
  input   signed [11:0] obs_samples_18;  // sfix12_En10
  input   signed [11:0] obs_samples_19;  // sfix12_En10
  input   signed [11:0] obs_samples_20;  // sfix12_En10
  input   signed [11:0] obs_samples_21;  // sfix12_En10
  input   signed [11:0] obs_samples_22;  // sfix12_En10
  input   signed [11:0] obs_samples_23;  // sfix12_En10
  input   signed [11:0] obs_samples_24;  // sfix12_En10
  input   signed [11:0] obs_samples_25;  // sfix12_En10
  input   signed [11:0] obs_samples_26;  // sfix12_En10
  input   signed [11:0] obs_samples_27;  // sfix12_En10
  input   signed [11:0] obs_samples_28;  // sfix12_En10
  input   signed [11:0] obs_samples_29;  // sfix12_En10
  input   signed [11:0] obs_samples_30;  // sfix12_En10
  input   signed [11:0] obs_samples_31;  // sfix12_En10
  output  [31:0] dopp_freq;  // ufix32_En5


  wire Constant_out1;
  wire signed [16:0] FFT_out1_re_0;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_1;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_2;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_3;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_4;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_5;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_6;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_7;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_8;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_9;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_10;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_11;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_12;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_13;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_14;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_15;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_16;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_17;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_18;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_19;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_20;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_21;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_22;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_23;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_24;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_25;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_26;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_27;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_28;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_29;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_30;  // sfix17_En10
  wire signed [16:0] FFT_out1_re_31;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_0;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_1;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_2;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_3;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_4;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_5;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_6;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_7;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_8;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_9;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_10;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_11;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_12;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_13;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_14;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_15;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_16;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_17;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_18;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_19;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_20;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_21;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_22;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_23;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_24;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_25;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_26;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_27;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_28;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_29;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_30;  // sfix17_En10
  wire signed [16:0] FFT_out1_im_31;  // sfix17_En10
  wire signed [16:0] Complex_to_Real_Imag_out1 [0:31];  // sfix17_En10 [32]
  wire signed [16:0] Complex_to_Real_Imag_out2 [0:31];  // sfix17_En10 [32]
  wire signed [17:0] Add_add_cast;  // sfix18_En10
  wire signed [17:0] Add_add_cast_1;  // sfix18_En10
  wire signed [17:0] Add_add_cast_2;  // sfix18_En10
  wire signed [17:0] Add_add_cast_3;  // sfix18_En10
  wire signed [17:0] Add_add_cast_4;  // sfix18_En10
  wire signed [17:0] Add_add_cast_5;  // sfix18_En10
  wire signed [17:0] Add_add_cast_6;  // sfix18_En10
  wire signed [17:0] Add_add_cast_7;  // sfix18_En10
  wire signed [17:0] Add_add_cast_8;  // sfix18_En10
  wire signed [17:0] Add_add_cast_9;  // sfix18_En10
  wire signed [17:0] Add_add_cast_10;  // sfix18_En10
  wire signed [17:0] Add_add_cast_11;  // sfix18_En10
  wire signed [17:0] Add_add_cast_12;  // sfix18_En10
  wire signed [17:0] Add_add_cast_13;  // sfix18_En10
  wire signed [17:0] Add_add_cast_14;  // sfix18_En10
  wire signed [17:0] Add_add_cast_15;  // sfix18_En10
  wire signed [17:0] Add_add_cast_16;  // sfix18_En10
  wire signed [17:0] Add_add_cast_17;  // sfix18_En10
  wire signed [17:0] Add_add_cast_18;  // sfix18_En10
  wire signed [17:0] Add_add_cast_19;  // sfix18_En10
  wire signed [17:0] Add_add_cast_20;  // sfix18_En10
  wire signed [17:0] Add_add_cast_21;  // sfix18_En10
  wire signed [17:0] Add_add_cast_22;  // sfix18_En10
  wire signed [17:0] Add_add_cast_23;  // sfix18_En10
  wire signed [17:0] Add_add_cast_24;  // sfix18_En10
  wire signed [17:0] Add_add_cast_25;  // sfix18_En10
  wire signed [17:0] Add_add_cast_26;  // sfix18_En10
  wire signed [17:0] Add_add_cast_27;  // sfix18_En10
  wire signed [17:0] Add_add_cast_28;  // sfix18_En10
  wire signed [17:0] Add_add_cast_29;  // sfix18_En10
  wire signed [17:0] Add_add_cast_30;  // sfix18_En10
  wire signed [17:0] Add_add_cast_31;  // sfix18_En10
  wire signed [17:0] Add_add_cast_32;  // sfix18_En10
  wire signed [17:0] Add_add_cast_33;  // sfix18_En10
  wire signed [17:0] Add_add_cast_34;  // sfix18_En10
  wire signed [17:0] Add_add_cast_35;  // sfix18_En10
  wire signed [17:0] Add_add_cast_36;  // sfix18_En10
  wire signed [17:0] Add_add_cast_37;  // sfix18_En10
  wire signed [17:0] Add_add_cast_38;  // sfix18_En10
  wire signed [17:0] Add_add_cast_39;  // sfix18_En10
  wire signed [17:0] Add_add_cast_40;  // sfix18_En10
  wire signed [17:0] Add_add_cast_41;  // sfix18_En10
  wire signed [17:0] Add_add_cast_42;  // sfix18_En10
  wire signed [17:0] Add_add_cast_43;  // sfix18_En10
  wire signed [17:0] Add_add_cast_44;  // sfix18_En10
  wire signed [17:0] Add_add_cast_45;  // sfix18_En10
  wire signed [17:0] Add_add_cast_46;  // sfix18_En10
  wire signed [17:0] Add_add_cast_47;  // sfix18_En10
  wire signed [17:0] Add_add_cast_48;  // sfix18_En10
  wire signed [17:0] Add_add_cast_49;  // sfix18_En10
  wire signed [17:0] Add_add_cast_50;  // sfix18_En10
  wire signed [17:0] Add_add_cast_51;  // sfix18_En10
  wire signed [17:0] Add_add_cast_52;  // sfix18_En10
  wire signed [17:0] Add_add_cast_53;  // sfix18_En10
  wire signed [17:0] Add_add_cast_54;  // sfix18_En10
  wire signed [17:0] Add_add_cast_55;  // sfix18_En10
  wire signed [17:0] Add_add_cast_56;  // sfix18_En10
  wire signed [17:0] Add_add_cast_57;  // sfix18_En10
  wire signed [17:0] Add_add_cast_58;  // sfix18_En10
  wire signed [17:0] Add_add_cast_59;  // sfix18_En10
  wire signed [17:0] Add_add_cast_60;  // sfix18_En10
  wire signed [17:0] Add_add_cast_61;  // sfix18_En10
  wire signed [17:0] Add_add_cast_62;  // sfix18_En10
  wire signed [17:0] Add_add_cast_63;  // sfix18_En10
  wire signed [17:0] Add_out1 [0:31];  // sfix18_En10 [32]
  wire signed [31:0] Data_Type_Conversion_out1 [0:31];  // sfix32_En32 [32]
  wire [31:0] f;  // ufix32_En5


  assign Constant_out1 = 1'b1;



  FFT u_FFT (.clk(clk),
             .reset(reset),
             .enb(enb),
             .dataIn_0(obs_samples_0),  // sfix12_En10
             .dataIn_1(obs_samples_1),  // sfix12_En10
             .dataIn_2(obs_samples_2),  // sfix12_En10
             .dataIn_3(obs_samples_3),  // sfix12_En10
             .dataIn_4(obs_samples_4),  // sfix12_En10
             .dataIn_5(obs_samples_5),  // sfix12_En10
             .dataIn_6(obs_samples_6),  // sfix12_En10
             .dataIn_7(obs_samples_7),  // sfix12_En10
             .dataIn_8(obs_samples_8),  // sfix12_En10
             .dataIn_9(obs_samples_9),  // sfix12_En10
             .dataIn_10(obs_samples_10),  // sfix12_En10
             .dataIn_11(obs_samples_11),  // sfix12_En10
             .dataIn_12(obs_samples_12),  // sfix12_En10
             .dataIn_13(obs_samples_13),  // sfix12_En10
             .dataIn_14(obs_samples_14),  // sfix12_En10
             .dataIn_15(obs_samples_15),  // sfix12_En10
             .dataIn_16(obs_samples_16),  // sfix12_En10
             .dataIn_17(obs_samples_17),  // sfix12_En10
             .dataIn_18(obs_samples_18),  // sfix12_En10
             .dataIn_19(obs_samples_19),  // sfix12_En10
             .dataIn_20(obs_samples_20),  // sfix12_En10
             .dataIn_21(obs_samples_21),  // sfix12_En10
             .dataIn_22(obs_samples_22),  // sfix12_En10
             .dataIn_23(obs_samples_23),  // sfix12_En10
             .dataIn_24(obs_samples_24),  // sfix12_En10
             .dataIn_25(obs_samples_25),  // sfix12_En10
             .dataIn_26(obs_samples_26),  // sfix12_En10
             .dataIn_27(obs_samples_27),  // sfix12_En10
             .dataIn_28(obs_samples_28),  // sfix12_En10
             .dataIn_29(obs_samples_29),  // sfix12_En10
             .dataIn_30(obs_samples_30),  // sfix12_En10
             .dataIn_31(obs_samples_31),  // sfix12_En10
             .validIn(Constant_out1),
             .dataOut_re_0(FFT_out1_re_0),  // sfix17_En10
             .dataOut_re_1(FFT_out1_re_1),  // sfix17_En10
             .dataOut_re_2(FFT_out1_re_2),  // sfix17_En10
             .dataOut_re_3(FFT_out1_re_3),  // sfix17_En10
             .dataOut_re_4(FFT_out1_re_4),  // sfix17_En10
             .dataOut_re_5(FFT_out1_re_5),  // sfix17_En10
             .dataOut_re_6(FFT_out1_re_6),  // sfix17_En10
             .dataOut_re_7(FFT_out1_re_7),  // sfix17_En10
             .dataOut_re_8(FFT_out1_re_8),  // sfix17_En10
             .dataOut_re_9(FFT_out1_re_9),  // sfix17_En10
             .dataOut_re_10(FFT_out1_re_10),  // sfix17_En10
             .dataOut_re_11(FFT_out1_re_11),  // sfix17_En10
             .dataOut_re_12(FFT_out1_re_12),  // sfix17_En10
             .dataOut_re_13(FFT_out1_re_13),  // sfix17_En10
             .dataOut_re_14(FFT_out1_re_14),  // sfix17_En10
             .dataOut_re_15(FFT_out1_re_15),  // sfix17_En10
             .dataOut_re_16(FFT_out1_re_16),  // sfix17_En10
             .dataOut_re_17(FFT_out1_re_17),  // sfix17_En10
             .dataOut_re_18(FFT_out1_re_18),  // sfix17_En10
             .dataOut_re_19(FFT_out1_re_19),  // sfix17_En10
             .dataOut_re_20(FFT_out1_re_20),  // sfix17_En10
             .dataOut_re_21(FFT_out1_re_21),  // sfix17_En10
             .dataOut_re_22(FFT_out1_re_22),  // sfix17_En10
             .dataOut_re_23(FFT_out1_re_23),  // sfix17_En10
             .dataOut_re_24(FFT_out1_re_24),  // sfix17_En10
             .dataOut_re_25(FFT_out1_re_25),  // sfix17_En10
             .dataOut_re_26(FFT_out1_re_26),  // sfix17_En10
             .dataOut_re_27(FFT_out1_re_27),  // sfix17_En10
             .dataOut_re_28(FFT_out1_re_28),  // sfix17_En10
             .dataOut_re_29(FFT_out1_re_29),  // sfix17_En10
             .dataOut_re_30(FFT_out1_re_30),  // sfix17_En10
             .dataOut_re_31(FFT_out1_re_31),  // sfix17_En10
             .dataOut_im_0(FFT_out1_im_0),  // sfix17_En10
             .dataOut_im_1(FFT_out1_im_1),  // sfix17_En10
             .dataOut_im_2(FFT_out1_im_2),  // sfix17_En10
             .dataOut_im_3(FFT_out1_im_3),  // sfix17_En10
             .dataOut_im_4(FFT_out1_im_4),  // sfix17_En10
             .dataOut_im_5(FFT_out1_im_5),  // sfix17_En10
             .dataOut_im_6(FFT_out1_im_6),  // sfix17_En10
             .dataOut_im_7(FFT_out1_im_7),  // sfix17_En10
             .dataOut_im_8(FFT_out1_im_8),  // sfix17_En10
             .dataOut_im_9(FFT_out1_im_9),  // sfix17_En10
             .dataOut_im_10(FFT_out1_im_10),  // sfix17_En10
             .dataOut_im_11(FFT_out1_im_11),  // sfix17_En10
             .dataOut_im_12(FFT_out1_im_12),  // sfix17_En10
             .dataOut_im_13(FFT_out1_im_13),  // sfix17_En10
             .dataOut_im_14(FFT_out1_im_14),  // sfix17_En10
             .dataOut_im_15(FFT_out1_im_15),  // sfix17_En10
             .dataOut_im_16(FFT_out1_im_16),  // sfix17_En10
             .dataOut_im_17(FFT_out1_im_17),  // sfix17_En10
             .dataOut_im_18(FFT_out1_im_18),  // sfix17_En10
             .dataOut_im_19(FFT_out1_im_19),  // sfix17_En10
             .dataOut_im_20(FFT_out1_im_20),  // sfix17_En10
             .dataOut_im_21(FFT_out1_im_21),  // sfix17_En10
             .dataOut_im_22(FFT_out1_im_22),  // sfix17_En10
             .dataOut_im_23(FFT_out1_im_23),  // sfix17_En10
             .dataOut_im_24(FFT_out1_im_24),  // sfix17_En10
             .dataOut_im_25(FFT_out1_im_25),  // sfix17_En10
             .dataOut_im_26(FFT_out1_im_26),  // sfix17_En10
             .dataOut_im_27(FFT_out1_im_27),  // sfix17_En10
             .dataOut_im_28(FFT_out1_im_28),  // sfix17_En10
             .dataOut_im_29(FFT_out1_im_29),  // sfix17_En10
             .dataOut_im_30(FFT_out1_im_30),  // sfix17_En10
             .dataOut_im_31(FFT_out1_im_31)  // sfix17_En10
             );

  assign Complex_to_Real_Imag_out1[0] = FFT_out1_re_0;
  assign Complex_to_Real_Imag_out1[1] = FFT_out1_re_1;
  assign Complex_to_Real_Imag_out1[2] = FFT_out1_re_2;
  assign Complex_to_Real_Imag_out1[3] = FFT_out1_re_3;
  assign Complex_to_Real_Imag_out1[4] = FFT_out1_re_4;
  assign Complex_to_Real_Imag_out1[5] = FFT_out1_re_5;
  assign Complex_to_Real_Imag_out1[6] = FFT_out1_re_6;
  assign Complex_to_Real_Imag_out1[7] = FFT_out1_re_7;
  assign Complex_to_Real_Imag_out1[8] = FFT_out1_re_8;
  assign Complex_to_Real_Imag_out1[9] = FFT_out1_re_9;
  assign Complex_to_Real_Imag_out1[10] = FFT_out1_re_10;
  assign Complex_to_Real_Imag_out1[11] = FFT_out1_re_11;
  assign Complex_to_Real_Imag_out1[12] = FFT_out1_re_12;
  assign Complex_to_Real_Imag_out1[13] = FFT_out1_re_13;
  assign Complex_to_Real_Imag_out1[14] = FFT_out1_re_14;
  assign Complex_to_Real_Imag_out1[15] = FFT_out1_re_15;
  assign Complex_to_Real_Imag_out1[16] = FFT_out1_re_16;
  assign Complex_to_Real_Imag_out1[17] = FFT_out1_re_17;
  assign Complex_to_Real_Imag_out1[18] = FFT_out1_re_18;
  assign Complex_to_Real_Imag_out1[19] = FFT_out1_re_19;
  assign Complex_to_Real_Imag_out1[20] = FFT_out1_re_20;
  assign Complex_to_Real_Imag_out1[21] = FFT_out1_re_21;
  assign Complex_to_Real_Imag_out1[22] = FFT_out1_re_22;
  assign Complex_to_Real_Imag_out1[23] = FFT_out1_re_23;
  assign Complex_to_Real_Imag_out1[24] = FFT_out1_re_24;
  assign Complex_to_Real_Imag_out1[25] = FFT_out1_re_25;
  assign Complex_to_Real_Imag_out1[26] = FFT_out1_re_26;
  assign Complex_to_Real_Imag_out1[27] = FFT_out1_re_27;
  assign Complex_to_Real_Imag_out1[28] = FFT_out1_re_28;
  assign Complex_to_Real_Imag_out1[29] = FFT_out1_re_29;
  assign Complex_to_Real_Imag_out1[30] = FFT_out1_re_30;
  assign Complex_to_Real_Imag_out1[31] = FFT_out1_re_31;

  assign Complex_to_Real_Imag_out2[0] = FFT_out1_im_0;
  assign Complex_to_Real_Imag_out2[1] = FFT_out1_im_1;
  assign Complex_to_Real_Imag_out2[2] = FFT_out1_im_2;
  assign Complex_to_Real_Imag_out2[3] = FFT_out1_im_3;
  assign Complex_to_Real_Imag_out2[4] = FFT_out1_im_4;
  assign Complex_to_Real_Imag_out2[5] = FFT_out1_im_5;
  assign Complex_to_Real_Imag_out2[6] = FFT_out1_im_6;
  assign Complex_to_Real_Imag_out2[7] = FFT_out1_im_7;
  assign Complex_to_Real_Imag_out2[8] = FFT_out1_im_8;
  assign Complex_to_Real_Imag_out2[9] = FFT_out1_im_9;
  assign Complex_to_Real_Imag_out2[10] = FFT_out1_im_10;
  assign Complex_to_Real_Imag_out2[11] = FFT_out1_im_11;
  assign Complex_to_Real_Imag_out2[12] = FFT_out1_im_12;
  assign Complex_to_Real_Imag_out2[13] = FFT_out1_im_13;
  assign Complex_to_Real_Imag_out2[14] = FFT_out1_im_14;
  assign Complex_to_Real_Imag_out2[15] = FFT_out1_im_15;
  assign Complex_to_Real_Imag_out2[16] = FFT_out1_im_16;
  assign Complex_to_Real_Imag_out2[17] = FFT_out1_im_17;
  assign Complex_to_Real_Imag_out2[18] = FFT_out1_im_18;
  assign Complex_to_Real_Imag_out2[19] = FFT_out1_im_19;
  assign Complex_to_Real_Imag_out2[20] = FFT_out1_im_20;
  assign Complex_to_Real_Imag_out2[21] = FFT_out1_im_21;
  assign Complex_to_Real_Imag_out2[22] = FFT_out1_im_22;
  assign Complex_to_Real_Imag_out2[23] = FFT_out1_im_23;
  assign Complex_to_Real_Imag_out2[24] = FFT_out1_im_24;
  assign Complex_to_Real_Imag_out2[25] = FFT_out1_im_25;
  assign Complex_to_Real_Imag_out2[26] = FFT_out1_im_26;
  assign Complex_to_Real_Imag_out2[27] = FFT_out1_im_27;
  assign Complex_to_Real_Imag_out2[28] = FFT_out1_im_28;
  assign Complex_to_Real_Imag_out2[29] = FFT_out1_im_29;
  assign Complex_to_Real_Imag_out2[30] = FFT_out1_im_30;
  assign Complex_to_Real_Imag_out2[31] = FFT_out1_im_31;

  assign Add_add_cast = {Complex_to_Real_Imag_out1[0][16], Complex_to_Real_Imag_out1[0]};
  assign Add_add_cast_1 = {Complex_to_Real_Imag_out2[0][16], Complex_to_Real_Imag_out2[0]};
  assign Add_out1[0] = Add_add_cast + Add_add_cast_1;
  assign Add_add_cast_2 = {Complex_to_Real_Imag_out1[1][16], Complex_to_Real_Imag_out1[1]};
  assign Add_add_cast_3 = {Complex_to_Real_Imag_out2[1][16], Complex_to_Real_Imag_out2[1]};
  assign Add_out1[1] = Add_add_cast_2 + Add_add_cast_3;
  assign Add_add_cast_4 = {Complex_to_Real_Imag_out1[2][16], Complex_to_Real_Imag_out1[2]};
  assign Add_add_cast_5 = {Complex_to_Real_Imag_out2[2][16], Complex_to_Real_Imag_out2[2]};
  assign Add_out1[2] = Add_add_cast_4 + Add_add_cast_5;
  assign Add_add_cast_6 = {Complex_to_Real_Imag_out1[3][16], Complex_to_Real_Imag_out1[3]};
  assign Add_add_cast_7 = {Complex_to_Real_Imag_out2[3][16], Complex_to_Real_Imag_out2[3]};
  assign Add_out1[3] = Add_add_cast_6 + Add_add_cast_7;
  assign Add_add_cast_8 = {Complex_to_Real_Imag_out1[4][16], Complex_to_Real_Imag_out1[4]};
  assign Add_add_cast_9 = {Complex_to_Real_Imag_out2[4][16], Complex_to_Real_Imag_out2[4]};
  assign Add_out1[4] = Add_add_cast_8 + Add_add_cast_9;
  assign Add_add_cast_10 = {Complex_to_Real_Imag_out1[5][16], Complex_to_Real_Imag_out1[5]};
  assign Add_add_cast_11 = {Complex_to_Real_Imag_out2[5][16], Complex_to_Real_Imag_out2[5]};
  assign Add_out1[5] = Add_add_cast_10 + Add_add_cast_11;
  assign Add_add_cast_12 = {Complex_to_Real_Imag_out1[6][16], Complex_to_Real_Imag_out1[6]};
  assign Add_add_cast_13 = {Complex_to_Real_Imag_out2[6][16], Complex_to_Real_Imag_out2[6]};
  assign Add_out1[6] = Add_add_cast_12 + Add_add_cast_13;
  assign Add_add_cast_14 = {Complex_to_Real_Imag_out1[7][16], Complex_to_Real_Imag_out1[7]};
  assign Add_add_cast_15 = {Complex_to_Real_Imag_out2[7][16], Complex_to_Real_Imag_out2[7]};
  assign Add_out1[7] = Add_add_cast_14 + Add_add_cast_15;
  assign Add_add_cast_16 = {Complex_to_Real_Imag_out1[8][16], Complex_to_Real_Imag_out1[8]};
  assign Add_add_cast_17 = {Complex_to_Real_Imag_out2[8][16], Complex_to_Real_Imag_out2[8]};
  assign Add_out1[8] = Add_add_cast_16 + Add_add_cast_17;
  assign Add_add_cast_18 = {Complex_to_Real_Imag_out1[9][16], Complex_to_Real_Imag_out1[9]};
  assign Add_add_cast_19 = {Complex_to_Real_Imag_out2[9][16], Complex_to_Real_Imag_out2[9]};
  assign Add_out1[9] = Add_add_cast_18 + Add_add_cast_19;
  assign Add_add_cast_20 = {Complex_to_Real_Imag_out1[10][16], Complex_to_Real_Imag_out1[10]};
  assign Add_add_cast_21 = {Complex_to_Real_Imag_out2[10][16], Complex_to_Real_Imag_out2[10]};
  assign Add_out1[10] = Add_add_cast_20 + Add_add_cast_21;
  assign Add_add_cast_22 = {Complex_to_Real_Imag_out1[11][16], Complex_to_Real_Imag_out1[11]};
  assign Add_add_cast_23 = {Complex_to_Real_Imag_out2[11][16], Complex_to_Real_Imag_out2[11]};
  assign Add_out1[11] = Add_add_cast_22 + Add_add_cast_23;
  assign Add_add_cast_24 = {Complex_to_Real_Imag_out1[12][16], Complex_to_Real_Imag_out1[12]};
  assign Add_add_cast_25 = {Complex_to_Real_Imag_out2[12][16], Complex_to_Real_Imag_out2[12]};
  assign Add_out1[12] = Add_add_cast_24 + Add_add_cast_25;
  assign Add_add_cast_26 = {Complex_to_Real_Imag_out1[13][16], Complex_to_Real_Imag_out1[13]};
  assign Add_add_cast_27 = {Complex_to_Real_Imag_out2[13][16], Complex_to_Real_Imag_out2[13]};
  assign Add_out1[13] = Add_add_cast_26 + Add_add_cast_27;
  assign Add_add_cast_28 = {Complex_to_Real_Imag_out1[14][16], Complex_to_Real_Imag_out1[14]};
  assign Add_add_cast_29 = {Complex_to_Real_Imag_out2[14][16], Complex_to_Real_Imag_out2[14]};
  assign Add_out1[14] = Add_add_cast_28 + Add_add_cast_29;
  assign Add_add_cast_30 = {Complex_to_Real_Imag_out1[15][16], Complex_to_Real_Imag_out1[15]};
  assign Add_add_cast_31 = {Complex_to_Real_Imag_out2[15][16], Complex_to_Real_Imag_out2[15]};
  assign Add_out1[15] = Add_add_cast_30 + Add_add_cast_31;
  assign Add_add_cast_32 = {Complex_to_Real_Imag_out1[16][16], Complex_to_Real_Imag_out1[16]};
  assign Add_add_cast_33 = {Complex_to_Real_Imag_out2[16][16], Complex_to_Real_Imag_out2[16]};
  assign Add_out1[16] = Add_add_cast_32 + Add_add_cast_33;
  assign Add_add_cast_34 = {Complex_to_Real_Imag_out1[17][16], Complex_to_Real_Imag_out1[17]};
  assign Add_add_cast_35 = {Complex_to_Real_Imag_out2[17][16], Complex_to_Real_Imag_out2[17]};
  assign Add_out1[17] = Add_add_cast_34 + Add_add_cast_35;
  assign Add_add_cast_36 = {Complex_to_Real_Imag_out1[18][16], Complex_to_Real_Imag_out1[18]};
  assign Add_add_cast_37 = {Complex_to_Real_Imag_out2[18][16], Complex_to_Real_Imag_out2[18]};
  assign Add_out1[18] = Add_add_cast_36 + Add_add_cast_37;
  assign Add_add_cast_38 = {Complex_to_Real_Imag_out1[19][16], Complex_to_Real_Imag_out1[19]};
  assign Add_add_cast_39 = {Complex_to_Real_Imag_out2[19][16], Complex_to_Real_Imag_out2[19]};
  assign Add_out1[19] = Add_add_cast_38 + Add_add_cast_39;
  assign Add_add_cast_40 = {Complex_to_Real_Imag_out1[20][16], Complex_to_Real_Imag_out1[20]};
  assign Add_add_cast_41 = {Complex_to_Real_Imag_out2[20][16], Complex_to_Real_Imag_out2[20]};
  assign Add_out1[20] = Add_add_cast_40 + Add_add_cast_41;
  assign Add_add_cast_42 = {Complex_to_Real_Imag_out1[21][16], Complex_to_Real_Imag_out1[21]};
  assign Add_add_cast_43 = {Complex_to_Real_Imag_out2[21][16], Complex_to_Real_Imag_out2[21]};
  assign Add_out1[21] = Add_add_cast_42 + Add_add_cast_43;
  assign Add_add_cast_44 = {Complex_to_Real_Imag_out1[22][16], Complex_to_Real_Imag_out1[22]};
  assign Add_add_cast_45 = {Complex_to_Real_Imag_out2[22][16], Complex_to_Real_Imag_out2[22]};
  assign Add_out1[22] = Add_add_cast_44 + Add_add_cast_45;
  assign Add_add_cast_46 = {Complex_to_Real_Imag_out1[23][16], Complex_to_Real_Imag_out1[23]};
  assign Add_add_cast_47 = {Complex_to_Real_Imag_out2[23][16], Complex_to_Real_Imag_out2[23]};
  assign Add_out1[23] = Add_add_cast_46 + Add_add_cast_47;
  assign Add_add_cast_48 = {Complex_to_Real_Imag_out1[24][16], Complex_to_Real_Imag_out1[24]};
  assign Add_add_cast_49 = {Complex_to_Real_Imag_out2[24][16], Complex_to_Real_Imag_out2[24]};
  assign Add_out1[24] = Add_add_cast_48 + Add_add_cast_49;
  assign Add_add_cast_50 = {Complex_to_Real_Imag_out1[25][16], Complex_to_Real_Imag_out1[25]};
  assign Add_add_cast_51 = {Complex_to_Real_Imag_out2[25][16], Complex_to_Real_Imag_out2[25]};
  assign Add_out1[25] = Add_add_cast_50 + Add_add_cast_51;
  assign Add_add_cast_52 = {Complex_to_Real_Imag_out1[26][16], Complex_to_Real_Imag_out1[26]};
  assign Add_add_cast_53 = {Complex_to_Real_Imag_out2[26][16], Complex_to_Real_Imag_out2[26]};
  assign Add_out1[26] = Add_add_cast_52 + Add_add_cast_53;
  assign Add_add_cast_54 = {Complex_to_Real_Imag_out1[27][16], Complex_to_Real_Imag_out1[27]};
  assign Add_add_cast_55 = {Complex_to_Real_Imag_out2[27][16], Complex_to_Real_Imag_out2[27]};
  assign Add_out1[27] = Add_add_cast_54 + Add_add_cast_55;
  assign Add_add_cast_56 = {Complex_to_Real_Imag_out1[28][16], Complex_to_Real_Imag_out1[28]};
  assign Add_add_cast_57 = {Complex_to_Real_Imag_out2[28][16], Complex_to_Real_Imag_out2[28]};
  assign Add_out1[28] = Add_add_cast_56 + Add_add_cast_57;
  assign Add_add_cast_58 = {Complex_to_Real_Imag_out1[29][16], Complex_to_Real_Imag_out1[29]};
  assign Add_add_cast_59 = {Complex_to_Real_Imag_out2[29][16], Complex_to_Real_Imag_out2[29]};
  assign Add_out1[29] = Add_add_cast_58 + Add_add_cast_59;
  assign Add_add_cast_60 = {Complex_to_Real_Imag_out1[30][16], Complex_to_Real_Imag_out1[30]};
  assign Add_add_cast_61 = {Complex_to_Real_Imag_out2[30][16], Complex_to_Real_Imag_out2[30]};
  assign Add_out1[30] = Add_add_cast_60 + Add_add_cast_61;
  assign Add_add_cast_62 = {Complex_to_Real_Imag_out1[31][16], Complex_to_Real_Imag_out1[31]};
  assign Add_add_cast_63 = {Complex_to_Real_Imag_out2[31][16], Complex_to_Real_Imag_out2[31]};
  assign Add_out1[31] = Add_add_cast_62 + Add_add_cast_63;



  assign Data_Type_Conversion_out1[0] = {Add_out1[0][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[1] = {Add_out1[1][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[2] = {Add_out1[2][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[3] = {Add_out1[3][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[4] = {Add_out1[4][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[5] = {Add_out1[5][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[6] = {Add_out1[6][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[7] = {Add_out1[7][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[8] = {Add_out1[8][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[9] = {Add_out1[9][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[10] = {Add_out1[10][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[11] = {Add_out1[11][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[12] = {Add_out1[12][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[13] = {Add_out1[13][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[14] = {Add_out1[14][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[15] = {Add_out1[15][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[16] = {Add_out1[16][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[17] = {Add_out1[17][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[18] = {Add_out1[18][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[19] = {Add_out1[19][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[20] = {Add_out1[20][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[21] = {Add_out1[21][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[22] = {Add_out1[22][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[23] = {Add_out1[23][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[24] = {Add_out1[24][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[25] = {Add_out1[25][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[26] = {Add_out1[26][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[27] = {Add_out1[27][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[28] = {Add_out1[28][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[29] = {Add_out1[29][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[30] = {Add_out1[30][9:0], 22'b0000000000000000000000};
  assign Data_Type_Conversion_out1[31] = {Add_out1[31][9:0], 22'b0000000000000000000000};



  Doppler_Calculation u_Doppler_Calculation (.u_0(Data_Type_Conversion_out1[0]),  // sfix32_En32
                                             .u_1(Data_Type_Conversion_out1[1]),  // sfix32_En32
                                             .u_2(Data_Type_Conversion_out1[2]),  // sfix32_En32
                                             .u_3(Data_Type_Conversion_out1[3]),  // sfix32_En32
                                             .u_4(Data_Type_Conversion_out1[4]),  // sfix32_En32
                                             .u_5(Data_Type_Conversion_out1[5]),  // sfix32_En32
                                             .u_6(Data_Type_Conversion_out1[6]),  // sfix32_En32
                                             .u_7(Data_Type_Conversion_out1[7]),  // sfix32_En32
                                             .u_8(Data_Type_Conversion_out1[8]),  // sfix32_En32
                                             .u_9(Data_Type_Conversion_out1[9]),  // sfix32_En32
                                             .u_10(Data_Type_Conversion_out1[10]),  // sfix32_En32
                                             .u_11(Data_Type_Conversion_out1[11]),  // sfix32_En32
                                             .u_12(Data_Type_Conversion_out1[12]),  // sfix32_En32
                                             .u_13(Data_Type_Conversion_out1[13]),  // sfix32_En32
                                             .u_14(Data_Type_Conversion_out1[14]),  // sfix32_En32
                                             .u_15(Data_Type_Conversion_out1[15]),  // sfix32_En32
                                             .u_16(Data_Type_Conversion_out1[16]),  // sfix32_En32
                                             .u_17(Data_Type_Conversion_out1[17]),  // sfix32_En32
                                             .u_18(Data_Type_Conversion_out1[18]),  // sfix32_En32
                                             .u_19(Data_Type_Conversion_out1[19]),  // sfix32_En32
                                             .u_20(Data_Type_Conversion_out1[20]),  // sfix32_En32
                                             .u_21(Data_Type_Conversion_out1[21]),  // sfix32_En32
                                             .u_22(Data_Type_Conversion_out1[22]),  // sfix32_En32
                                             .u_23(Data_Type_Conversion_out1[23]),  // sfix32_En32
                                             .u_24(Data_Type_Conversion_out1[24]),  // sfix32_En32
                                             .u_25(Data_Type_Conversion_out1[25]),  // sfix32_En32
                                             .u_26(Data_Type_Conversion_out1[26]),  // sfix32_En32
                                             .u_27(Data_Type_Conversion_out1[27]),  // sfix32_En32
                                             .u_28(Data_Type_Conversion_out1[28]),  // sfix32_En32
                                             .u_29(Data_Type_Conversion_out1[29]),  // sfix32_En32
                                             .u_30(Data_Type_Conversion_out1[30]),  // sfix32_En32
                                             .u_31(Data_Type_Conversion_out1[31]),  // sfix32_En32
                                             .f(f)  // ufix32_En5
                                             );

  assign dopp_freq = f;

endmodule  // Doppler_Processor

