cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('RSP/Buffer','user1');
hilite_system('RSP/Buffer/Data Type Conversion1','user1');
hilite_system('RSP/Buffer/Delay','user1');
hilite_system('RSP/Buffer/HDL Counter','user1');
hilite_system('RSP/Buffer/buffer','user1');
hilite_system('RSP/Buffer/vector initialization','user1');
hilite_system('RSP/Data Type Conversion1','user1');
hilite_system('RSP/Correlator','user1');
hilite_system('RSP/Rx_Signal','user1');
hilite_system('RSP/Rx_Signal_Counter','user1');
hilite_system('RSP/Switch','user1');
hilite_system('RSP/Data Type Conversion3','user1');
hilite_system('RSP/Buffer/Data Type Conversion2','user1');
hilite_system('RSP/Tx Signal','user1');
hilite_system('RSP/Zero Signal','user1');
