// -------------------------------------------------------------
// 
// File Name: C:\Users\acer\OneDrive\Documents\ITS CAK V2\Magang\BRIN\Progress\Matlab Simulink\HDL Coder\proyek\RSP\RSP\RSP\RADIX22FFT_SDNF1_3_block4.v
// Created: 2023-09-27 04:10:36
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RADIX22FFT_SDNF1_3_block4
// Source Path: RSP/RSP/Velocity Processor/Doppler Processing/Doppler Processor/FFT/RADIX22FFT_SDNF1_3
// Hierarchy Level: 5
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RADIX22FFT_SDNF1_3_block4
          (clk,
           reset,
           enb,
           twdlXdin_10_re,
           twdlXdin_10_im,
           twdlXdin_14_re,
           twdlXdin_14_im,
           twdlXdin_1_vld,
           dout_11_re,
           dout_11_im,
           dout_12_re,
           dout_12_im);


  input   clk;
  input   reset;
  input   enb;
  input   signed [14:0] twdlXdin_10_re;  // sfix15_En10
  input   signed [14:0] twdlXdin_10_im;  // sfix15_En10
  input   signed [14:0] twdlXdin_14_re;  // sfix15_En10
  input   signed [14:0] twdlXdin_14_im;  // sfix15_En10
  input   twdlXdin_1_vld;
  output  signed [14:0] dout_11_re;  // sfix15_En10
  output  signed [14:0] dout_11_im;  // sfix15_En10
  output  signed [14:0] dout_12_re;  // sfix15_En10
  output  signed [14:0] dout_12_im;  // sfix15_En10


  reg signed [15:0] Radix22ButterflyG1_NF_btf1_re_reg;  // sfix16
  reg signed [15:0] Radix22ButterflyG1_NF_btf1_im_reg;  // sfix16
  reg signed [15:0] Radix22ButterflyG1_NF_btf2_re_reg;  // sfix16
  reg signed [15:0] Radix22ButterflyG1_NF_btf2_im_reg;  // sfix16
  reg  Radix22ButterflyG1_NF_dinXtwdl_vld_dly1;
  reg signed [15:0] Radix22ButterflyG1_NF_btf1_re_reg_next;  // sfix16_En10
  reg signed [15:0] Radix22ButterflyG1_NF_btf1_im_reg_next;  // sfix16_En10
  reg signed [15:0] Radix22ButterflyG1_NF_btf2_re_reg_next;  // sfix16_En10
  reg signed [15:0] Radix22ButterflyG1_NF_btf2_im_reg_next;  // sfix16_En10
  reg  Radix22ButterflyG1_NF_dinXtwdl_vld_dly1_next;
  reg signed [14:0] dout_11_re_1;  // sfix15_En10
  reg signed [14:0] dout_11_im_1;  // sfix15_En10
  reg signed [14:0] dout_12_re_1;  // sfix15_En10
  reg signed [14:0] dout_12_im_1;  // sfix15_En10
  reg  dout_11_vld;
  reg signed [15:0] Radix22ButterflyG1_NF_add_cast;  // sfix16_En10
  reg signed [15:0] Radix22ButterflyG1_NF_add_cast_0;  // sfix16_En10
  reg signed [15:0] Radix22ButterflyG1_NF_sub_cast;  // sfix16_En10
  reg signed [15:0] Radix22ButterflyG1_NF_sub_cast_0;  // sfix16_En10
  reg signed [15:0] Radix22ButterflyG1_NF_add_cast_1;  // sfix16_En10
  reg signed [15:0] Radix22ButterflyG1_NF_add_cast_2;  // sfix16_En10
  reg signed [15:0] Radix22ButterflyG1_NF_sub_cast_1;  // sfix16_En10
  reg signed [15:0] Radix22ButterflyG1_NF_sub_cast_2;  // sfix16_En10


  // Radix22ButterflyG1_NF
  always @(posedge clk or posedge reset)
    begin : Radix22ButterflyG1_NF_process
      if (reset == 1'b1) begin
        Radix22ButterflyG1_NF_btf1_re_reg <= 16'sb0000000000000000;
        Radix22ButterflyG1_NF_btf1_im_reg <= 16'sb0000000000000000;
        Radix22ButterflyG1_NF_btf2_re_reg <= 16'sb0000000000000000;
        Radix22ButterflyG1_NF_btf2_im_reg <= 16'sb0000000000000000;
        Radix22ButterflyG1_NF_dinXtwdl_vld_dly1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Radix22ButterflyG1_NF_btf1_re_reg <= Radix22ButterflyG1_NF_btf1_re_reg_next;
          Radix22ButterflyG1_NF_btf1_im_reg <= Radix22ButterflyG1_NF_btf1_im_reg_next;
          Radix22ButterflyG1_NF_btf2_re_reg <= Radix22ButterflyG1_NF_btf2_re_reg_next;
          Radix22ButterflyG1_NF_btf2_im_reg <= Radix22ButterflyG1_NF_btf2_im_reg_next;
          Radix22ButterflyG1_NF_dinXtwdl_vld_dly1 <= Radix22ButterflyG1_NF_dinXtwdl_vld_dly1_next;
        end
      end
    end

  always @(Radix22ButterflyG1_NF_btf1_im_reg, Radix22ButterflyG1_NF_btf1_re_reg,
       Radix22ButterflyG1_NF_btf2_im_reg, Radix22ButterflyG1_NF_btf2_re_reg,
       Radix22ButterflyG1_NF_dinXtwdl_vld_dly1, twdlXdin_10_im, twdlXdin_10_re,
       twdlXdin_14_im, twdlXdin_14_re, twdlXdin_1_vld) begin
    Radix22ButterflyG1_NF_add_cast = 16'sb0000000000000000;
    Radix22ButterflyG1_NF_add_cast_0 = 16'sb0000000000000000;
    Radix22ButterflyG1_NF_sub_cast = 16'sb0000000000000000;
    Radix22ButterflyG1_NF_sub_cast_0 = 16'sb0000000000000000;
    Radix22ButterflyG1_NF_add_cast_1 = 16'sb0000000000000000;
    Radix22ButterflyG1_NF_add_cast_2 = 16'sb0000000000000000;
    Radix22ButterflyG1_NF_sub_cast_1 = 16'sb0000000000000000;
    Radix22ButterflyG1_NF_sub_cast_2 = 16'sb0000000000000000;
    Radix22ButterflyG1_NF_btf1_re_reg_next = Radix22ButterflyG1_NF_btf1_re_reg;
    Radix22ButterflyG1_NF_btf1_im_reg_next = Radix22ButterflyG1_NF_btf1_im_reg;
    Radix22ButterflyG1_NF_btf2_re_reg_next = Radix22ButterflyG1_NF_btf2_re_reg;
    Radix22ButterflyG1_NF_btf2_im_reg_next = Radix22ButterflyG1_NF_btf2_im_reg;
    Radix22ButterflyG1_NF_dinXtwdl_vld_dly1_next = twdlXdin_1_vld;
    if (twdlXdin_1_vld) begin
      Radix22ButterflyG1_NF_add_cast = {twdlXdin_10_re[14], twdlXdin_10_re};
      Radix22ButterflyG1_NF_add_cast_0 = {twdlXdin_14_re[14], twdlXdin_14_re};
      Radix22ButterflyG1_NF_btf1_re_reg_next = Radix22ButterflyG1_NF_add_cast + Radix22ButterflyG1_NF_add_cast_0;
      Radix22ButterflyG1_NF_sub_cast = {twdlXdin_10_re[14], twdlXdin_10_re};
      Radix22ButterflyG1_NF_sub_cast_0 = {twdlXdin_14_re[14], twdlXdin_14_re};
      Radix22ButterflyG1_NF_btf2_re_reg_next = Radix22ButterflyG1_NF_sub_cast - Radix22ButterflyG1_NF_sub_cast_0;
      Radix22ButterflyG1_NF_add_cast_1 = {twdlXdin_10_im[14], twdlXdin_10_im};
      Radix22ButterflyG1_NF_add_cast_2 = {twdlXdin_14_im[14], twdlXdin_14_im};
      Radix22ButterflyG1_NF_btf1_im_reg_next = Radix22ButterflyG1_NF_add_cast_1 + Radix22ButterflyG1_NF_add_cast_2;
      Radix22ButterflyG1_NF_sub_cast_1 = {twdlXdin_10_im[14], twdlXdin_10_im};
      Radix22ButterflyG1_NF_sub_cast_2 = {twdlXdin_14_im[14], twdlXdin_14_im};
      Radix22ButterflyG1_NF_btf2_im_reg_next = Radix22ButterflyG1_NF_sub_cast_1 - Radix22ButterflyG1_NF_sub_cast_2;
    end
    dout_11_re_1 = Radix22ButterflyG1_NF_btf1_re_reg[14:0];
    dout_11_im_1 = Radix22ButterflyG1_NF_btf1_im_reg[14:0];
    dout_12_re_1 = Radix22ButterflyG1_NF_btf2_re_reg[14:0];
    dout_12_im_1 = Radix22ButterflyG1_NF_btf2_im_reg[14:0];
    dout_11_vld = Radix22ButterflyG1_NF_dinXtwdl_vld_dly1;
  end



  assign dout_11_re = dout_11_re_1;

  assign dout_11_im = dout_11_im_1;

  assign dout_12_re = dout_12_re_1;

  assign dout_12_im = dout_12_im_1;

endmodule  // RADIX22FFT_SDNF1_3_block4

