-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\IIR_Filter\IIR_Filter_pkg.vhd
-- Created: 2023-04-04 14:57:38
-- 
-- Generated by MATLAB 9.12 and HDL Coder 3.20
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE IIR_Filter_pkg IS
  TYPE vector_of_signed16 IS ARRAY (NATURAL RANGE <>) OF signed(15 DOWNTO 0);
END IIR_Filter_pkg;

