SLStudio.Utils.RemoveHighlighting(get_param('Tx_OFDM', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_Tx_OFDM', 'handle'));
annotate_port('gm_Tx_OFDM/Transmitter/IFFT', 1, 1, '');
annotate_port('Tx_OFDM/Transmitter/IFFT', 1, 1, '');
annotate_port('gm_Tx_OFDM/Transmitter/IFFT', 1, 1, '');
annotate_port('Tx_OFDM/Transmitter/IFFT', 1, 1, '');
annotate_port('gm_Tx_OFDM/Transmitter/Rectangular QAM Modulator Baseband', 1, 1, '');
annotate_port('Tx_OFDM/Transmitter/Rectangular QAM Modulator Baseband', 1, 1, '');
annotate_port('gm_Tx_OFDM/Transmitter/Rectangular QAM Modulator Baseband', 1, 1, '');
annotate_port('Tx_OFDM/Transmitter/Rectangular QAM Modulator Baseband', 1, 1, '');
annotate_port('gm_Tx_OFDM/Transmitter/Cosine HDL Optimized/Look-Up Table', 0, 1, '');
annotate_port('Tx_OFDM/Transmitter/Cosine HDL Optimized/cosine hdl/Look-Up Table', 0, 1, '');
annotate_port('gm_Tx_OFDM/Transmitter/Sine HDL Optimized/Look-Up Table', 0, 1, '');
annotate_port('Tx_OFDM/Transmitter/Sine HDL Optimized/sine hdl/Look-Up Table', 0, 1, '');
