open_system('Tx_OFDM');
open_system('gm_Tx_OFDM');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Tx_OFDM/Transmitter/OFDM Modulator1', 'user2');
annotate_port('gm_Tx_OFDM/Transmitter/OFDM Modulator1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('Tx_OFDM/Transmitter/OFDM Modulator1', 'user2');
annotate_port('Tx_OFDM/Transmitter/OFDM Modulator1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Tx_OFDM/Transmitter/Rectangular QAM Modulator Baseband', 'user2');
annotate_port('gm_Tx_OFDM/Transmitter/Rectangular QAM Modulator Baseband', 1, 1, 'Unsupported block for clock-rate pipelining');
hilite_system('Tx_OFDM/Transmitter/Rectangular QAM Modulator Baseband', 'user2');
annotate_port('Tx_OFDM/Transmitter/Rectangular QAM Modulator Baseband', 1, 1, 'Unsupported block for clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Tx_OFDM/Transmitter/Rectangular QAM Modulator Baseband', 'user2');
annotate_port('gm_Tx_OFDM/Transmitter/Rectangular QAM Modulator Baseband', 1, 1, 'Unsupported block for clock-rate pipelining');
hilite_system('Tx_OFDM/Transmitter/Rectangular QAM Modulator Baseband', 'user2');
annotate_port('Tx_OFDM/Transmitter/Rectangular QAM Modulator Baseband', 1, 1, 'Unsupported block for clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Tx_OFDM/Transmitter/OFDM Modulator1/OFDM Modulator1', 'user2');
annotate_port('gm_Tx_OFDM/Transmitter/OFDM Modulator1/OFDM Modulator1', 1, 1, 'Unsupported block for clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Tx_OFDM/Transmitter/OFDM Modulator1/OFDM Modulator1', 'user2');
annotate_port('gm_Tx_OFDM/Transmitter/OFDM Modulator1/OFDM Modulator1', 1, 1, 'Unsupported block for clock-rate pipelining');
hilite_system('Tx_OFDM/Transmitter/OFDM Modulator1', 'user2');
annotate_port('Tx_OFDM/Transmitter/OFDM Modulator1', 1, 1, 'Unsupported block for clock-rate pipelining');
