// -------------------------------------------------------------
// 
// File Name: C:\Users\acer\OneDrive\Documents\ITS CAK V2\Magang\BRIN\Progress\Matlab Simulink\HDL Coder\proyek\OFDM\Tx_OFDM_Verilog\Tx_OFDM\vector_initialization.v
// Created: 2023-06-11 16:01:44
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: vector_initialization
// Source Path: Tx_OFDM/Transmitter/QAM Modulator/QAM Buffer/vector initialization
// Hierarchy Level: 3
// 
// #codegen
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module vector_initialization
          (y_re_0,
           y_re_1,
           y_re_2,
           y_re_3,
           y_re_4,
           y_re_5,
           y_re_6,
           y_re_7,
           y_re_8,
           y_re_9,
           y_re_10,
           y_re_11,
           y_re_12,
           y_re_13,
           y_re_14,
           y_re_15,
           y_re_16,
           y_re_17,
           y_re_18,
           y_re_19,
           y_re_20,
           y_re_21,
           y_re_22,
           y_re_23,
           y_re_24,
           y_re_25,
           y_re_26,
           y_re_27,
           y_re_28,
           y_re_29,
           y_re_30,
           y_re_31,
           y_re_32,
           y_re_33,
           y_re_34,
           y_re_35,
           y_re_36,
           y_re_37,
           y_re_38,
           y_re_39,
           y_re_40,
           y_re_41,
           y_re_42,
           y_re_43,
           y_re_44,
           y_re_45,
           y_re_46,
           y_re_47,
           y_re_48,
           y_re_49,
           y_re_50,
           y_re_51,
           y_re_52,
           y_re_53,
           y_re_54,
           y_re_55,
           y_re_56,
           y_re_57,
           y_re_58,
           y_re_59,
           y_re_60,
           y_re_61,
           y_re_62,
           y_re_63,
           y_im_0,
           y_im_1,
           y_im_2,
           y_im_3,
           y_im_4,
           y_im_5,
           y_im_6,
           y_im_7,
           y_im_8,
           y_im_9,
           y_im_10,
           y_im_11,
           y_im_12,
           y_im_13,
           y_im_14,
           y_im_15,
           y_im_16,
           y_im_17,
           y_im_18,
           y_im_19,
           y_im_20,
           y_im_21,
           y_im_22,
           y_im_23,
           y_im_24,
           y_im_25,
           y_im_26,
           y_im_27,
           y_im_28,
           y_im_29,
           y_im_30,
           y_im_31,
           y_im_32,
           y_im_33,
           y_im_34,
           y_im_35,
           y_im_36,
           y_im_37,
           y_im_38,
           y_im_39,
           y_im_40,
           y_im_41,
           y_im_42,
           y_im_43,
           y_im_44,
           y_im_45,
           y_im_46,
           y_im_47,
           y_im_48,
           y_im_49,
           y_im_50,
           y_im_51,
           y_im_52,
           y_im_53,
           y_im_54,
           y_im_55,
           y_im_56,
           y_im_57,
           y_im_58,
           y_im_59,
           y_im_60,
           y_im_61,
           y_im_62,
           y_im_63);


  output  [63:0] y_re_0;  // double
  output  [63:0] y_re_1;  // double
  output  [63:0] y_re_2;  // double
  output  [63:0] y_re_3;  // double
  output  [63:0] y_re_4;  // double
  output  [63:0] y_re_5;  // double
  output  [63:0] y_re_6;  // double
  output  [63:0] y_re_7;  // double
  output  [63:0] y_re_8;  // double
  output  [63:0] y_re_9;  // double
  output  [63:0] y_re_10;  // double
  output  [63:0] y_re_11;  // double
  output  [63:0] y_re_12;  // double
  output  [63:0] y_re_13;  // double
  output  [63:0] y_re_14;  // double
  output  [63:0] y_re_15;  // double
  output  [63:0] y_re_16;  // double
  output  [63:0] y_re_17;  // double
  output  [63:0] y_re_18;  // double
  output  [63:0] y_re_19;  // double
  output  [63:0] y_re_20;  // double
  output  [63:0] y_re_21;  // double
  output  [63:0] y_re_22;  // double
  output  [63:0] y_re_23;  // double
  output  [63:0] y_re_24;  // double
  output  [63:0] y_re_25;  // double
  output  [63:0] y_re_26;  // double
  output  [63:0] y_re_27;  // double
  output  [63:0] y_re_28;  // double
  output  [63:0] y_re_29;  // double
  output  [63:0] y_re_30;  // double
  output  [63:0] y_re_31;  // double
  output  [63:0] y_re_32;  // double
  output  [63:0] y_re_33;  // double
  output  [63:0] y_re_34;  // double
  output  [63:0] y_re_35;  // double
  output  [63:0] y_re_36;  // double
  output  [63:0] y_re_37;  // double
  output  [63:0] y_re_38;  // double
  output  [63:0] y_re_39;  // double
  output  [63:0] y_re_40;  // double
  output  [63:0] y_re_41;  // double
  output  [63:0] y_re_42;  // double
  output  [63:0] y_re_43;  // double
  output  [63:0] y_re_44;  // double
  output  [63:0] y_re_45;  // double
  output  [63:0] y_re_46;  // double
  output  [63:0] y_re_47;  // double
  output  [63:0] y_re_48;  // double
  output  [63:0] y_re_49;  // double
  output  [63:0] y_re_50;  // double
  output  [63:0] y_re_51;  // double
  output  [63:0] y_re_52;  // double
  output  [63:0] y_re_53;  // double
  output  [63:0] y_re_54;  // double
  output  [63:0] y_re_55;  // double
  output  [63:0] y_re_56;  // double
  output  [63:0] y_re_57;  // double
  output  [63:0] y_re_58;  // double
  output  [63:0] y_re_59;  // double
  output  [63:0] y_re_60;  // double
  output  [63:0] y_re_61;  // double
  output  [63:0] y_re_62;  // double
  output  [63:0] y_re_63;  // double
  output  [63:0] y_im_0;  // double
  output  [63:0] y_im_1;  // double
  output  [63:0] y_im_2;  // double
  output  [63:0] y_im_3;  // double
  output  [63:0] y_im_4;  // double
  output  [63:0] y_im_5;  // double
  output  [63:0] y_im_6;  // double
  output  [63:0] y_im_7;  // double
  output  [63:0] y_im_8;  // double
  output  [63:0] y_im_9;  // double
  output  [63:0] y_im_10;  // double
  output  [63:0] y_im_11;  // double
  output  [63:0] y_im_12;  // double
  output  [63:0] y_im_13;  // double
  output  [63:0] y_im_14;  // double
  output  [63:0] y_im_15;  // double
  output  [63:0] y_im_16;  // double
  output  [63:0] y_im_17;  // double
  output  [63:0] y_im_18;  // double
  output  [63:0] y_im_19;  // double
  output  [63:0] y_im_20;  // double
  output  [63:0] y_im_21;  // double
  output  [63:0] y_im_22;  // double
  output  [63:0] y_im_23;  // double
  output  [63:0] y_im_24;  // double
  output  [63:0] y_im_25;  // double
  output  [63:0] y_im_26;  // double
  output  [63:0] y_im_27;  // double
  output  [63:0] y_im_28;  // double
  output  [63:0] y_im_29;  // double
  output  [63:0] y_im_30;  // double
  output  [63:0] y_im_31;  // double
  output  [63:0] y_im_32;  // double
  output  [63:0] y_im_33;  // double
  output  [63:0] y_im_34;  // double
  output  [63:0] y_im_35;  // double
  output  [63:0] y_im_36;  // double
  output  [63:0] y_im_37;  // double
  output  [63:0] y_im_38;  // double
  output  [63:0] y_im_39;  // double
  output  [63:0] y_im_40;  // double
  output  [63:0] y_im_41;  // double
  output  [63:0] y_im_42;  // double
  output  [63:0] y_im_43;  // double
  output  [63:0] y_im_44;  // double
  output  [63:0] y_im_45;  // double
  output  [63:0] y_im_46;  // double
  output  [63:0] y_im_47;  // double
  output  [63:0] y_im_48;  // double
  output  [63:0] y_im_49;  // double
  output  [63:0] y_im_50;  // double
  output  [63:0] y_im_51;  // double
  output  [63:0] y_im_52;  // double
  output  [63:0] y_im_53;  // double
  output  [63:0] y_im_54;  // double
  output  [63:0] y_im_55;  // double
  output  [63:0] y_im_56;  // double
  output  [63:0] y_im_57;  // double
  output  [63:0] y_im_58;  // double
  output  [63:0] y_im_59;  // double
  output  [63:0] y_im_60;  // double
  output  [63:0] y_im_61;  // double
  output  [63:0] y_im_62;  // double
  output  [63:0] y_im_63;  // double


  wire [63:0] y_re [0:63];  // ufix64 [64]
  wire [63:0] y_im [0:63];  // ufix64 [64]


  assign y_re[0] = 64'h3ff0000000000000;
  assign y_im[0] = 64'h0000000000000000;
  assign y_re[1] = 64'h3ff0000000000000;
  assign y_im[1] = 64'h0000000000000000;
  assign y_re[2] = 64'h3ff0000000000000;
  assign y_im[2] = 64'h0000000000000000;
  assign y_re[3] = 64'h3ff0000000000000;
  assign y_im[3] = 64'h0000000000000000;
  assign y_re[4] = 64'h3ff0000000000000;
  assign y_im[4] = 64'h0000000000000000;
  assign y_re[5] = 64'h3ff0000000000000;
  assign y_im[5] = 64'h0000000000000000;
  assign y_re[6] = 64'h3ff0000000000000;
  assign y_im[6] = 64'h0000000000000000;
  assign y_re[7] = 64'h3ff0000000000000;
  assign y_im[7] = 64'h0000000000000000;
  assign y_re[8] = 64'h3ff0000000000000;
  assign y_im[8] = 64'h0000000000000000;
  assign y_re[9] = 64'h3ff0000000000000;
  assign y_im[9] = 64'h0000000000000000;
  assign y_re[10] = 64'h3ff0000000000000;
  assign y_im[10] = 64'h0000000000000000;
  assign y_re[11] = 64'h3ff0000000000000;
  assign y_im[11] = 64'h0000000000000000;
  assign y_re[12] = 64'h3ff0000000000000;
  assign y_im[12] = 64'h0000000000000000;
  assign y_re[13] = 64'h3ff0000000000000;
  assign y_im[13] = 64'h0000000000000000;
  assign y_re[14] = 64'h3ff0000000000000;
  assign y_im[14] = 64'h0000000000000000;
  assign y_re[15] = 64'h3ff0000000000000;
  assign y_im[15] = 64'h0000000000000000;
  assign y_re[16] = 64'h3ff0000000000000;
  assign y_im[16] = 64'h0000000000000000;
  assign y_re[17] = 64'h3ff0000000000000;
  assign y_im[17] = 64'h0000000000000000;
  assign y_re[18] = 64'h3ff0000000000000;
  assign y_im[18] = 64'h0000000000000000;
  assign y_re[19] = 64'h3ff0000000000000;
  assign y_im[19] = 64'h0000000000000000;
  assign y_re[20] = 64'h3ff0000000000000;
  assign y_im[20] = 64'h0000000000000000;
  assign y_re[21] = 64'h3ff0000000000000;
  assign y_im[21] = 64'h0000000000000000;
  assign y_re[22] = 64'h3ff0000000000000;
  assign y_im[22] = 64'h0000000000000000;
  assign y_re[23] = 64'h3ff0000000000000;
  assign y_im[23] = 64'h0000000000000000;
  assign y_re[24] = 64'h3ff0000000000000;
  assign y_im[24] = 64'h0000000000000000;
  assign y_re[25] = 64'h3ff0000000000000;
  assign y_im[25] = 64'h0000000000000000;
  assign y_re[26] = 64'h3ff0000000000000;
  assign y_im[26] = 64'h0000000000000000;
  assign y_re[27] = 64'h3ff0000000000000;
  assign y_im[27] = 64'h0000000000000000;
  assign y_re[28] = 64'h3ff0000000000000;
  assign y_im[28] = 64'h0000000000000000;
  assign y_re[29] = 64'h3ff0000000000000;
  assign y_im[29] = 64'h0000000000000000;
  assign y_re[30] = 64'h3ff0000000000000;
  assign y_im[30] = 64'h0000000000000000;
  assign y_re[31] = 64'h3ff0000000000000;
  assign y_im[31] = 64'h0000000000000000;
  assign y_re[32] = 64'h3ff0000000000000;
  assign y_im[32] = 64'h0000000000000000;
  assign y_re[33] = 64'h3ff0000000000000;
  assign y_im[33] = 64'h0000000000000000;
  assign y_re[34] = 64'h3ff0000000000000;
  assign y_im[34] = 64'h0000000000000000;
  assign y_re[35] = 64'h3ff0000000000000;
  assign y_im[35] = 64'h0000000000000000;
  assign y_re[36] = 64'h3ff0000000000000;
  assign y_im[36] = 64'h0000000000000000;
  assign y_re[37] = 64'h3ff0000000000000;
  assign y_im[37] = 64'h0000000000000000;
  assign y_re[38] = 64'h3ff0000000000000;
  assign y_im[38] = 64'h0000000000000000;
  assign y_re[39] = 64'h3ff0000000000000;
  assign y_im[39] = 64'h0000000000000000;
  assign y_re[40] = 64'h3ff0000000000000;
  assign y_im[40] = 64'h0000000000000000;
  assign y_re[41] = 64'h3ff0000000000000;
  assign y_im[41] = 64'h0000000000000000;
  assign y_re[42] = 64'h3ff0000000000000;
  assign y_im[42] = 64'h0000000000000000;
  assign y_re[43] = 64'h3ff0000000000000;
  assign y_im[43] = 64'h0000000000000000;
  assign y_re[44] = 64'h3ff0000000000000;
  assign y_im[44] = 64'h0000000000000000;
  assign y_re[45] = 64'h3ff0000000000000;
  assign y_im[45] = 64'h0000000000000000;
  assign y_re[46] = 64'h3ff0000000000000;
  assign y_im[46] = 64'h0000000000000000;
  assign y_re[47] = 64'h3ff0000000000000;
  assign y_im[47] = 64'h0000000000000000;
  assign y_re[48] = 64'h3ff0000000000000;
  assign y_im[48] = 64'h0000000000000000;
  assign y_re[49] = 64'h3ff0000000000000;
  assign y_im[49] = 64'h0000000000000000;
  assign y_re[50] = 64'h3ff0000000000000;
  assign y_im[50] = 64'h0000000000000000;
  assign y_re[51] = 64'h3ff0000000000000;
  assign y_im[51] = 64'h0000000000000000;
  assign y_re[52] = 64'h3ff0000000000000;
  assign y_im[52] = 64'h0000000000000000;
  assign y_re[53] = 64'h3ff0000000000000;
  assign y_im[53] = 64'h0000000000000000;
  assign y_re[54] = 64'h3ff0000000000000;
  assign y_im[54] = 64'h0000000000000000;
  assign y_re[55] = 64'h3ff0000000000000;
  assign y_im[55] = 64'h0000000000000000;
  assign y_re[56] = 64'h3ff0000000000000;
  assign y_im[56] = 64'h0000000000000000;
  assign y_re[57] = 64'h3ff0000000000000;
  assign y_im[57] = 64'h0000000000000000;
  assign y_re[58] = 64'h3ff0000000000000;
  assign y_im[58] = 64'h0000000000000000;
  assign y_re[59] = 64'h3ff0000000000000;
  assign y_im[59] = 64'h0000000000000000;
  assign y_re[60] = 64'h3ff0000000000000;
  assign y_im[60] = 64'h0000000000000000;
  assign y_re[61] = 64'h3ff0000000000000;
  assign y_im[61] = 64'h0000000000000000;
  assign y_re[62] = 64'h3ff0000000000000;
  assign y_im[62] = 64'h0000000000000000;
  assign y_re[63] = 64'h3ff0000000000000;
  assign y_im[63] = 64'h0000000000000000;



  assign y_re_0 = y_re[0];

  assign y_re_1 = y_re[1];

  assign y_re_2 = y_re[2];

  assign y_re_3 = y_re[3];

  assign y_re_4 = y_re[4];

  assign y_re_5 = y_re[5];

  assign y_re_6 = y_re[6];

  assign y_re_7 = y_re[7];

  assign y_re_8 = y_re[8];

  assign y_re_9 = y_re[9];

  assign y_re_10 = y_re[10];

  assign y_re_11 = y_re[11];

  assign y_re_12 = y_re[12];

  assign y_re_13 = y_re[13];

  assign y_re_14 = y_re[14];

  assign y_re_15 = y_re[15];

  assign y_re_16 = y_re[16];

  assign y_re_17 = y_re[17];

  assign y_re_18 = y_re[18];

  assign y_re_19 = y_re[19];

  assign y_re_20 = y_re[20];

  assign y_re_21 = y_re[21];

  assign y_re_22 = y_re[22];

  assign y_re_23 = y_re[23];

  assign y_re_24 = y_re[24];

  assign y_re_25 = y_re[25];

  assign y_re_26 = y_re[26];

  assign y_re_27 = y_re[27];

  assign y_re_28 = y_re[28];

  assign y_re_29 = y_re[29];

  assign y_re_30 = y_re[30];

  assign y_re_31 = y_re[31];

  assign y_re_32 = y_re[32];

  assign y_re_33 = y_re[33];

  assign y_re_34 = y_re[34];

  assign y_re_35 = y_re[35];

  assign y_re_36 = y_re[36];

  assign y_re_37 = y_re[37];

  assign y_re_38 = y_re[38];

  assign y_re_39 = y_re[39];

  assign y_re_40 = y_re[40];

  assign y_re_41 = y_re[41];

  assign y_re_42 = y_re[42];

  assign y_re_43 = y_re[43];

  assign y_re_44 = y_re[44];

  assign y_re_45 = y_re[45];

  assign y_re_46 = y_re[46];

  assign y_re_47 = y_re[47];

  assign y_re_48 = y_re[48];

  assign y_re_49 = y_re[49];

  assign y_re_50 = y_re[50];

  assign y_re_51 = y_re[51];

  assign y_re_52 = y_re[52];

  assign y_re_53 = y_re[53];

  assign y_re_54 = y_re[54];

  assign y_re_55 = y_re[55];

  assign y_re_56 = y_re[56];

  assign y_re_57 = y_re[57];

  assign y_re_58 = y_re[58];

  assign y_re_59 = y_re[59];

  assign y_re_60 = y_re[60];

  assign y_re_61 = y_re[61];

  assign y_re_62 = y_re[62];

  assign y_re_63 = y_re[63];

  assign y_im_0 = y_im[0];

  assign y_im_1 = y_im[1];

  assign y_im_2 = y_im[2];

  assign y_im_3 = y_im[3];

  assign y_im_4 = y_im[4];

  assign y_im_5 = y_im[5];

  assign y_im_6 = y_im[6];

  assign y_im_7 = y_im[7];

  assign y_im_8 = y_im[8];

  assign y_im_9 = y_im[9];

  assign y_im_10 = y_im[10];

  assign y_im_11 = y_im[11];

  assign y_im_12 = y_im[12];

  assign y_im_13 = y_im[13];

  assign y_im_14 = y_im[14];

  assign y_im_15 = y_im[15];

  assign y_im_16 = y_im[16];

  assign y_im_17 = y_im[17];

  assign y_im_18 = y_im[18];

  assign y_im_19 = y_im[19];

  assign y_im_20 = y_im[20];

  assign y_im_21 = y_im[21];

  assign y_im_22 = y_im[22];

  assign y_im_23 = y_im[23];

  assign y_im_24 = y_im[24];

  assign y_im_25 = y_im[25];

  assign y_im_26 = y_im[26];

  assign y_im_27 = y_im[27];

  assign y_im_28 = y_im[28];

  assign y_im_29 = y_im[29];

  assign y_im_30 = y_im[30];

  assign y_im_31 = y_im[31];

  assign y_im_32 = y_im[32];

  assign y_im_33 = y_im[33];

  assign y_im_34 = y_im[34];

  assign y_im_35 = y_im[35];

  assign y_im_36 = y_im[36];

  assign y_im_37 = y_im[37];

  assign y_im_38 = y_im[38];

  assign y_im_39 = y_im[39];

  assign y_im_40 = y_im[40];

  assign y_im_41 = y_im[41];

  assign y_im_42 = y_im[42];

  assign y_im_43 = y_im[43];

  assign y_im_44 = y_im[44];

  assign y_im_45 = y_im[45];

  assign y_im_46 = y_im[46];

  assign y_im_47 = y_im[47];

  assign y_im_48 = y_im[48];

  assign y_im_49 = y_im[49];

  assign y_im_50 = y_im[50];

  assign y_im_51 = y_im[51];

  assign y_im_52 = y_im[52];

  assign y_im_53 = y_im[53];

  assign y_im_54 = y_im[54];

  assign y_im_55 = y_im[55];

  assign y_im_56 = y_im[56];

  assign y_im_57 = y_im[57];

  assign y_im_58 = y_im[58];

  assign y_im_59 = y_im[59];

  assign y_im_60 = y_im[60];

  assign y_im_61 = y_im[61];

  assign y_im_62 = y_im[62];

  assign y_im_63 = y_im[63];

endmodule  // vector_initialization

